"""build_name_calibration.py — each stock's OWN calibration record, on its page.  [R-REC-01]

Adopted 24-Aug-2026, per instruction ("we need to stop looking at stocks in a
country as a bulk — look at each stock individually"). Computes, for every
covered stock, its own backtest record under the LIVE production cone — how many
resolved three-month windows its history holds, and how often its middle (25-75)
and wide (5-95) bands actually caught the close — and writes ONE generated block
into assets/data.js:

    const CALIB = { "EGX:PHDC": {w: 57, in50: 47, in90: 89, through: "2026-05-31"}, ... };

keyed by the entry's exchange code (unique; ticker keys are not — EG ADIB vs
ADIBUAE share a code suffix). app.js renders it under the fan on every page.

Numbers are COMPUTED HERE, never typed: the in-band flags are the exact
fast_rescore algebra on the panels' invariant residuals under the live
market_profiles (nu, width_cal) — the same closed form the reshape work
verified against the stored panel flags at 99.4-100% agreement. Regeneration is
idempotent: the block is replaced between its markers on every run.

Verification (the JS rules): node --check on data.js, then load it and assert
CALIB covers every TICKERS entry — COUNT AGAINST THE KNOWN TOTAL, never trust
"0 skipped".
"""
import json
import os
import re
import subprocess
import sys

import numpy as np
import pandas as pd
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import market_profiles as MP                                     # noqa: E402

DATA_JS = os.path.join(ROOT, "assets", "data.js")
MARK_A = "// ==== NAME_CALIBRATION (generated by engine/build_name_calibration.py — do not hand-edit) ===="
MARK_B = "// ==== END NAME_CALIBRATION ===="
PREFIX_MARKET = {"EGX": "EG", "ADX": "AE", "DFM": "AE", "TADAWUL": "SA",
                 "QSE": "QA", "KRX": "KR", "NSE": "IN", "NASDAQ": "US"}
SPECIAL_RAW = {"2POINTZERO": "TWOPOINTZERO",
               "ALRAJHI": "RAJHI"}     # Tadawul codes are numeric (TADAWUL:1120)


def tq(p, nu):
    if nu >= 200:
        return float(stats.norm.ppf(p))
    return float(stats.t.ppf(p, nu) / np.sqrt(nu / (nu - 2)))


def tickers_index():
    """(key, code) for every TICKERS entry, read by loading data.js in node."""
    out = subprocess.run(
        ["node", "-e",
         "const fs=require('fs'),vm=require('vm');"
         "let s=fs.readFileSync(process.argv[1],'utf8');"
         "s+='\\n;globalThis.__T=TICKERS;';const c={window:{}};"
         "vm.createContext(c);vm.runInContext(s,c);"
         "console.log(JSON.stringify(Object.entries(c.__T).map(([k,v])=>[k,v.code])));",
         DATA_JS],
        capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def record_for(code, key):
    pfx, suffix = code.split(":", 1)
    mkt = PREFIX_MARKET[pfx]
    prof = MP.PROFILES[mkt]
    for cand in (SPECIAL_RAW.get(suffix), SPECIAL_RAW.get(key), suffix, key,
                 key.upper(), suffix.upper()):
        if cand and os.path.exists(f"{HERE}/panels/{mkt}_{cand}_3m.csv"):
            raw = cand
            break
    else:
        return None
    r = pd.read_csv(f"{HERE}/panels/{mkt}_{raw}_3m.csv")
    r = r[np.isfinite(r["u"]) & (r["sigma_h"] > 0)]
    if not len(r):
        return None
    cal, nu = float(prof.width_cal), float(prof.nu)
    a = r["alpha"] / r["sigma_h"]
    u = r["u"] - a * (cal - 1)
    in50 = ((cal * tq(.25, nu) <= u) & (u <= cal * tq(.75, nu))).mean()
    in90 = ((cal * tq(.05, nu) <= u) & (u <= cal * tq(.95, nu))).mean()
    return dict(w=int(len(r)), in50=int(round(100 * in50)),
                in90=int(round(100 * in90)),
                through=str(pd.to_datetime(r["grade_date"]).max().date()))


def main():
    idx = tickers_index()
    total = len(idx)
    recs, missing = {}, []
    for key, code in idx:
        rec = record_for(code, key)
        if rec is None:
            missing.append(f"{key} ({code})")
        else:
            recs[code] = rec
    if missing:
        sys.exit(f"FAIL — {len(missing)} of {total} TICKERS entries have no "
                 f"panel record: {', '.join(missing)}. Every entry must resolve "
                 "or be explicitly removed here — silence is the defect.")
    lines = [MARK_A,
             "const CALIB = {"]
    for code in sorted(recs):
        r = recs[code]
        lines.append(f'  "{code}": {{w: {r["w"]}, in50: {r["in50"]}, '
                     f'in90: {r["in90"]}, through: "{r["through"]}"}},')
    lines.append("};")
    lines.append(MARK_B)
    block = "\n".join(lines)

    src = open(DATA_JS).read()
    if MARK_A in src:
        pat = re.escape(MARK_A) + r".*?" + re.escape(MARK_B)
        new = re.sub(pat, block, src, count=1, flags=re.S)
        assert new != src or block in src, "marker replace produced no change"
        src = new
    else:
        src = src.rstrip("\n") + "\n\n" + block + "\n"
    open(DATA_JS, "w").write(src)

    subprocess.run(["node", "--check", DATA_JS], check=True)
    out = subprocess.run(
        ["node", "-e",
         "const fs=require('fs'),vm=require('vm');"
         "let s=fs.readFileSync(process.argv[1],'utf8');"
         "s+='\\n;globalThis.__T=TICKERS;globalThis.__C=CALIB;';const c={window:{}};"
         "vm.createContext(c);vm.runInContext(s,c);"
         "const T=c.__T,C=c.__C;const miss=Object.values(T).map(v=>v.code)"
         ".filter(cd=>!C[cd]);"
         "console.log(JSON.stringify({tickers:Object.keys(T).length,"
         "calib:Object.keys(C).length,missing:miss}));",
         DATA_JS], capture_output=True, text=True, check=True)
    chk = json.loads(out.stdout)
    assert chk["tickers"] == total and chk["calib"] == total and not chk["missing"], chk
    print(f"CALIB written and verified: {chk['calib']} records for "
          f"{chk['tickers']} TICKERS entries, 0 missing (counted against total {total})")


if __name__ == "__main__":
    main()
