"""Generate Lessons_Register.md from lessons_register.py.

The register is GENERATED, never typed. This project has twice had two copies of
the same rules drift apart — the two protocol documents, and a page that stated
a fact it was also supposed to remember. A document that states something which
moves must not be the thing that remembers it.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import lessons_register as LR

OUT = os.path.join(HERE, "Lessons_Register.md")

ORIGIN_WORDS = {
    "walk_forward_fundamental": "fundamental walk-forward test",
    "walk_forward_price": "price-engine walk-forward test",
    "critique": "outside critique",
    "self_audit": "self-audit",
    "build": "found while building",
}


def population():
    """What evidence actually exists on disk, counted rather than remembered.

    Two different tests are both called a walk-forward and the first edition of
    this register conflated them, which understated the evidence base badly.
    Both are counted here, from the directories and files themselves.
    """
    import csv, glob
    fund = sorted(d[:-len("_walkforward")].upper() for d in os.listdir(HERE)
                  if d.endswith("_walkforward")
                  and os.path.isdir(os.path.join(HERE, d)))
    price, origins = [], 0
    for f in sorted(glob.glob(os.path.join(HERE, "*_study",
                                           "backtest_rows.csv"))):
        n = sum(1 for _ in csv.DictReader(open(f)))
        if n:
            price.append((os.path.basename(os.path.dirname(f))[:-6].upper(), n))
            origins += n
    return {"fundamental": fund, "price": price, "price_origins": origins}

HEAD = """# The Lessons Register

**Every lesson this project has learned, in plain language, and how far each one
travels.**

> **NOTHING IN THIS REGISTER BINDS ANY STUDY.** It is a record, not a gate. No
> standing rule refers to it and no quality gate consults it, deliberately —
> the walk-forward method that produced its strongest lessons has not itself
> been validated. One company has been through a run; that run's own training
> record states its corrections rest on two starting points, its intervals are
> wide with several straddling zero, and its observations are not independent.
> The house rule is that nothing enters the method without surviving the same
> out-of-sample test the forecasts must survive, and a finding measured on one
> name has not survived it. **Every walk-forward lesson is therefore marked
> PROVISIONAL** and stays that way until the method is validated across more
> names. Read this register to think with; do not cite it as authority.

GENERATED FROM `lessons_register.py` — do not edit this file by hand. Edits here
are overwritten; `scripts/check_lessons_register.py` fails the build if the two
disagree.

---

## How to read this

A lesson is useless until you know how far it carries. Every entry is therefore
tagged with one of three scopes, and the difference is not a matter of taste.

| scope | means | who must read it |
|---|---|---|
| **ALL** | true of every study we will ever run — about method, arithmetic, or how work gets checked | every study, every time |
| **CLASS** | true of every company that works the same way (every off-plan developer, every telecom operator) | the next study of that class only |
| **STOCK** | true of this one company and nothing else — a quirk of its disclosure, history or accounting | that company's next update only |

**Applying a STOCK lesson to another company is superstition.** Applying an ALL
lesson is mandatory. The middle category is where most of the value is, and it
is the one that takes longest to fill.

Every lesson also records **how it was learned**, because the strength of the
evidence differs enormously:

- **walk-forward test** — measured against real outcomes across many starting
  points. The strongest evidence this project produces.
- **outside critique** — found by an external reviewer of a delivered study.
- **self-audit** — found by re-examining our own work before anyone else read it.
- **found while building** — usually because a check reported clean on something
  it was not actually looking at.

Where two lessons disagree, the walk-forward one wins.

And every lesson carries **what would overturn it**. A lesson with no falsifier
is a habit, not a finding, and habits are how a method quietly stops being
tested.

---

## What is in here, and what is honestly missing

"""


def _row(x):
    lines = []
    lines.append("### %s · %s\n" % (x["id"], x["headline"]))
    lines.append(x["plain"] + "\n")
    if x["scope"] == "ALL":
        who = "**Applies to:** every study"
    elif x["scope"] == "CLASS":
        who = "**Applies to:** every %s" % x["applies_to"]
    else:
        who = "**Applies to:** %s only" % x["applies_to"]
    tail = "" if x["status"] == "adopted" else "  ·  **status: %s**" % x["status"]
    lines.append("%s  ·  *Learned from:* %s, %s%s\n"
                 % (who, ORIGIN_WORDS[x["origin"]], x["source"], tail))
    lines.append("> **What it cost, or how we know.** %s\n" % x["evidence"])
    lines.append("> **What would overturn it.** %s\n" % x["overturned_by"])
    return "\n".join(lines) + "\n"


def build():
    LR.assert_lessons_register()
    c = LR.counts()
    body = [HEAD]
    pop = population()
    body.append(
        "**%d lessons**, of which %d bind on every study, %d on a class of "
        "company, and %d on a single name.\n\n"
        "By how they were learned: %d from fundamental walk-forward testing, "
        "%d from price-engine walk-forward testing, %d from outside critiques, "
        "%d from self-audits, %d found while building.\n\n"
        "### Two different tests are both called a walk-forward\n\n"
        "They test different machinery on different evidence, and the first "
        "edition of this register conflated them — which understated the "
        "evidence base badly and is recorded here rather than quietly "
        "corrected.\n\n"
        "| | what it tests | names | resolved forecasts |\n|---|---|---|---|\n"
        "| **Fundamental** | the forecasting method — project each driver from "
        "a past origin, score revenue, cost and profit against what happened |"
        " %d (%s) | 10 origins x 5 horizons |\n"
        "| **Price engine** | the probability cone — strike it at a past "
        "origin and score band coverage and a proper score against a naive "
        "rule | %d | %d |\n\n"
        "**The price engine is well tested; the fundamental method is not.** "
        "%d names carry price-engine evidence, including DU (%s forecasts) and "
        "GBCO (%s). The fundamental method has been through a full training run "
        "on %s alone, and that run's own record states its corrections rest on "
        "two starting points, its intervals are wide with several straddling "
        "zero, and its observations are not independent. **Every lesson from "
        "the fundamental method is therefore marked PROVISIONAL**; price-engine "
        "lessons are not, because they rest on %d forecasts across %d names.\n"
        % (c["total"], c["ALL"], c["CLASS"], c["STOCK"],
           c["by_origin"]["walk_forward_fundamental"],
           c["by_origin"]["walk_forward_price"], c["by_origin"]["critique"],
           c["by_origin"]["self_audit"], c["by_origin"]["build"],
           len(pop["fundamental"]), ", ".join(pop["fundamental"]),
           len(pop["price"]), pop["price_origins"], len(pop["price"]),
           dict(pop["price"]).get("DU", "no"),
           dict(pop["price"]).get("GBCO", "no"),
           " and ".join(pop["fundamental"]),
           pop["price_origins"], len(pop["price"])))

    outstanding = [x for x in LR.LESSONS if x["status"] == "outstanding"]
    if outstanding:
        body.append("\n**Not yet acted on (%d):** %s. These are recorded as "
                    "open rather than quietly carried as done.\n"
                    % (len(outstanding),
                       ", ".join("%s (%s)" % (x["id"], x["headline"].rstrip("."))
                                 for x in outstanding)))

    body.append("\n---\n\n# Lessons that bind on EVERY study\n\n"
                "*Read these before starting any study, of any company, in any "
                "market.*\n\n")
    for x in sorted([l for l in LR.LESSONS if l["scope"] == "ALL"],
                    key=lambda y: y["id"]):
        body.append(_row(x))

    body.append("\n---\n\n# Lessons that bind on a CLASS of company\n\n"
                "*Read the section for the class being studied. Do not read "
                "across classes — a rule true of developers is not evidence "
                "about airlines.*\n")
    for k in LR.CLASSES:
        rows = sorted([l for l in LR.LESSONS
                       if l["scope"] == "CLASS" and l["applies_to"] == k],
                      key=lambda y: y["id"])
        if not rows:
            continue
        body.append("\n## %s\n\n" % (k[0].upper() + k[1:]))
        for x in rows:
            body.append(_row(x))

    body.append("\n---\n\n# Lessons that bind on ONE company\n\n"
                "*Read only the section for the company being updated. These do "
                "not generalise and must not be applied to another name.*\n")
    for t in sorted({l["applies_to"] for l in LR.LESSONS
                     if l["scope"] == "STOCK"}):
        body.append("\n## %s\n\n" % t)
        for x in sorted([l for l in LR.LESSONS
                         if l["scope"] == "STOCK" and l["applies_to"] == t],
                        key=lambda y: y["id"]):
            body.append(_row(x))

    body.append("\n---\n\n## Adding a lesson\n\n"
                "A walk-forward run, a critique response or a QC gate that "
                "produced a finding worth keeping appends it to "
                "`lessons_register.py` and regenerates this file in the same "
                "commit. Every entry needs a plain-English statement, a scope, "
                "the evidence, and what would overturn it — the module refuses "
                "an entry missing any of them, and refuses a class name that is "
                "not registered.\n\n"
                "**Choosing the scope is the judgement, and getting it wrong is "
                "costly in both directions.** Too narrow and the next study "
                "repeats the mistake. Too broad and a company's quirk becomes a "
                "house rule nobody can dislodge. When genuinely unsure, record "
                "it at the narrower scope and widen it when a second company "
                "shows the same thing — one observation is not a pattern.\n")
    return "".join(body)


if __name__ == "__main__":
    text = build()
    open(OUT, "w").write(text)
    print("wrote %s (%d chars)" % (os.path.basename(OUT), len(text)))
    c = LR.counts()
    print("  ALL %d · CLASS %d · STOCK %d · total %d"
          % (c["ALL"], c["CLASS"], c["STOCK"], c["total"]))
