#!/usr/bin/env python3
"""Criterion 3 clause F — the decomposition, GENERATED.

[R-ENF-06]: an artefact every reader consumes and NOTHING WRITES is a number frozen
at the date somebody last typed it. It will not announce itself, it survives every
rebuild, and it wears the appearance of a computed record while being a memory. The
first version of this decomposition was produced by a script typed into a shell and
committed as JSON; that is precisely the shape that rule exists to refuse, so the
generator exists and the artefact is rebuilt from it.

WHAT THE CLAUSE ASKS: whether the residual contemporaneous bias attributes to a NAMED
lever. The lever is [R-ANCHOR-01 CLAUSE THREE] — a forecast rate climbing past
everything the company has ever FILED. A mechanical lens cannot name a mechanism for
such a rise, being forbidden judgement drivers by construction, so the rise is a claim
nothing in the lens is entitled to make.

IT IS AN ATTRIBUTION AND NEVER A PROMOTED LEVER. The pre-registration fixes six levers
in order before any score existed and this is not among them; a cap is a correction
factor and [R-FCAL-01] refuses one over a specification error. `cap_filed_peak`
defaults False everywhere and no scoring reading passes it, so nothing here can reach
a published figure.

    python3 clause_f_decomposition.py            rebuild the artefact
    python3 clause_f_decomposition.py --check    fail if it is not reproducible
"""
from __future__ import annotations

import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))

import cashflow_lens as L   # noqa: E402

OUT = os.path.join(HERE, "CLAUSE_F_DECOMPOSITION_08-09-2026.json")

# THE DECLARED READING, taken from the scorer rather than retyped, so the
# decomposition and the score cannot describe different runs.
READING = dict(maintenance="gordon", arcc_unit_fix="fisher")


def build():
    base, _ = L.run(**READING)
    capped, _ = L.run(cap_filed_peak=True, **READING)
    bi = {(r["ticker"], r["origin"]): r for r in base}
    ci = {(r["ticker"], r["origin"]): r for r in capped}
    if not bi:
        raise SystemExit("FATAL: the declared reading produced no cell — an empty "
                         "result is not a clean result [R-ENF-04]")
    lb = [math.log(r["fv"] / r["price"]) for r in base]
    lc = [math.log(r["fv"] / r["price"]) for r in capped]
    mb, mc = sum(lb) / len(lb), sum(lc) / len(lc)

    cells = []
    for k in sorted(bi):
        if k not in ci:
            continue
        pk, why = L.filed_peak_margin(k[0], k[1])
        moved = abs(bi[k]["fv"] - ci[k]["fv"]) > 1e-9
        cells.append({"ticker": k[0], "origin": k[1],
                      "filed_peak_margin": pk, "peak_unreadable": why,
                      "fv": bi[k]["fv"], "fv_held_to_filed_peak": ci[k]["fv"],
                      "log_move": math.log(ci[k]["fv"] / bi[k]["fv"]) if moved else 0.0,
                      "breaches_filed_record": bool(moved)})
    unread = [c for c in cells if c["filed_peak_margin"] is None]
    if len(unread) == len(cells):
        raise SystemExit("FATAL: no cell resolved a filed peak — that is the adapter "
                         "breaking, not the book having no margins [R-ENF-04]")

    return {
     "_": "Criterion 3 clause F — the decomposition that attributes the residual "
          "contemporaneous bias to a NAMED lever. GENERATED by "
          "clause_f_decomposition.py; never hand-edited.",
     "the_lever": "[R-ANCHOR-01 CLAUSE THREE] — a forecast rate that climbs past "
          "everything the company has ever FILED is a claim, named and sourced from a "
          "closed list of mechanisms. A MECHANICAL LENS CANNOT NAME ONE BY "
          "CONSTRUCTION: it is forbidden judgement drivers, and a mechanism is a "
          "judgement. So a mechanical projection rising past the filed record is "
          "asserting something nothing in it is entitled to assert, and that is a "
          "lever with a standing rule and a gate behind it rather than a parameter "
          "somebody chose.",
     "what_this_is_not": "IT IS AN ATTRIBUTION, NEVER A PROMOTED LEVER. The "
          "pre-registration fixes six levers in order before any score existed and "
          "this is not among them. NOTHING HERE MOVES A PUBLISHED FAIR VALUE: "
          "cap_filed_peak defaults False and no scoring reading passes it.",
     "point_in_time": "The peak is AS AT THE ORIGIN, never as at today — a later good "
          "year must not license an earlier forecast that could not have known about it.",
     "adapters": "One NAMED adapter per run, never a guessed convention: five runs "
          "carry five shapes and the first draft of this reader resolved on exactly "
          "one name and reported the other four as carrying no margin — an absent "
          "answer in a clean answer's clothes [R-ENF-04], [L-355] in the instrument.",
     "reading": "DECLARED (%s)" % ", ".join("%s=%s" % kv for kv in sorted(READING.items())),
     "pooled_bias": mb,
     "pooled_bias_held_to_filed_peak": mc,
     "attributed_share": (mb - mc) / mb if mb else None,
     "n_cells": len(cells),
     "n_breaching": sum(1 for c in cells if c["breaches_filed_record"]),
     "n_peak_unreadable": len(unread),
     "concentration": "The attribution is CONCENTRATED and saying so is part of it: "
          "one cell carries most of it.",
     "cells": cells,
    }


def main(argv):
    doc = build()
    if "--check" in argv:
        if not os.path.exists(OUT):
            print("FAILED — the artefact is absent and this generator writes it")
            return 1
        have = json.load(open(OUT, encoding="utf-8"))
        # Compare the FIGURES, not the prose: a reworded note is not a stale record.
        keys = ("pooled_bias", "pooled_bias_held_to_filed_peak", "attributed_share",
                "n_cells", "n_breaching", "cells")
        drift = [k for k in keys
                 if json.dumps(have.get(k), sort_keys=True, default=float)
                 != json.dumps(doc.get(k), sort_keys=True, default=float)]
        if drift:
            print("FAILED — the committed decomposition no longer reproduces: %s"
                  % ", ".join(drift))
            return 1
        print("clause F decomposition reproduces — bias %+.4f -> %+.4f, %.1f%% "
              "attributed on %d of %d cells"
              % (doc["pooled_bias"], doc["pooled_bias_held_to_filed_peak"],
                 100 * doc["attributed_share"], doc["n_breaching"], doc["n_cells"]))
        return 0
    json.dump(doc, open(OUT, "w", encoding="utf-8"), indent=1)
    print("wrote %s — bias %+.4f -> %+.4f, %.1f%% attributed on %d of %d cells"
          % (os.path.basename(OUT), doc["pooled_bias"],
             doc["pooled_bias_held_to_filed_peak"],
             100 * doc["attributed_share"], doc["n_breaching"], doc["n_cells"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
