#!/usr/bin/env python3
"""ADIB — the projected-versus-actual income statement, side by side, for EVERY origin.

[R-FCAL-01 §4] requires this for every origin, not for a selection of them. INTERNAL.
GENERATED — never hand-edited.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import panel, bottom_up as bu, score, diagnose  # noqa: E402

ROWS = [('fin_income', 'Income from Murabaha, Musharaka, Mudaraba and similar'),
        ('cost_funds', 'Cost of deposits and similar costs'),
        ('net_funds', '  NET INCOME FROM FUNDS  (output)'),
        ('net_fees', 'Net fees and commission income'),
        ('other_nii', 'Other non-interest income (derived block)'),
        ('admin', 'Administrative expenses'),
        ('other_op', 'Other operating income/(expenses)'),
        ('ecl', 'Impairment / expected credit losses'),
        ('pbt', '  PROFIT BEFORE TAX  (output)'),
        ('tax', 'Income tax'),
        ('np', '  NET PROFIT  (output)'),
        ('np_parent', '  ATTRIBUTABLE TO THE BANK  (output)'),
        ('fin_customers', 'Memo: net financing to customers'),
        ('cust_deposits', "Memo: customers' deposits"),
        ('total_assets', 'Memo: total assets')]


def fmt(x):
    return '—' if x is None else '{:,.0f}'.format(x)


def main():
    out = ['# ADIB (EGX) — projected versus actual, every origin, every matured horizon',
           '',
           'GENERATED by `build_reader.py`. INTERNAL — never shown to a reader.',
           '',
           'EGP thousands. `ratio` is projected / actual; 1.000 is exact. Every origin the',
           'run tested is here, including the two the method fails on.', '']
    for o in bu.ORIGINS:
        m = bu.build(o)
        meta = m['_meta']
        out += ['## Origin FY%d' % o, '',
                'Drivers read at this origin, from data published on or before 31-Dec-%d:' % o,
                '',
                '| driver | value |', '|---|---|',
                '| share of Egyptian system credit (R2, held flat) | %.3f%% |' % (100 * meta['share_of_system']),
                '| financing / deposits (R3) | %.3f |' % meta['ldr'],
                '| assets / deposits (R4) | %.3f |' % meta['assets_per_dep'],
                '| asset yield on average assets (R6) | %.3f%% |' % (100 * meta['asset_yield']),
                '| cost of funds on average interest-bearing liabilities (R7) | %.3f%% |' % (100 * meta['cost_of_funds']),
                '| net fees / average assets (R8) | %.3f%% |' % (100 * meta['fee_ratio']),
                '| other non-interest income / average assets (R9) | %.3f%% |' % (100 * meta['onii_ratio']),
                '| cost of risk on average financing (R12) | %.3f%% |' % (100 * meta['cost_of_risk']),
                '| effective tax rate (R13 primary) | %.1f%% |' % (100 * meta['tax_rate']),
                '| overhead branch (R10) | %s |' % meta['admin_branch'],
                '| system-credit trailing CAGR (R1) | %.1f%% |' % (100 * (meta['credit_cagr'] or 0)),
                '| trailing inflation (R15) | %.1f%% |' % (100 * (meta['cpi_trailing'] or 0)),
                '']
        yrs = [y for y in sorted(k for k in m if isinstance(k, int)) if y <= bu.LAST]
        if not yrs:
            out += ['_No matured horizon._', '']
            continue
        head = '| line | ' + ' | '.join('FY%d proj | FY%d act | ratio' % (y, y) for y in yrs) + ' |'
        out += [head, '|' + '---|' * (1 + 3 * len(yrs))]
        for f, label in ROWS:
            cells = []
            for y in yrs:
                p = m[y].get(f)
                a = score.actual(y, f)
                r = (p / a) if (a not in (None, 0)) else None
                cells += [fmt(p), fmt(a), ('%.3f' % r) if r is not None else '—']
            out.append('| %s | %s |' % (label, ' | '.join(cells)))
        out.append('')
    open(os.path.join(HERE, 'adib_IS_projected_vs_actual_all_origins.md'), 'w',
         encoding='utf-8').write('\n'.join(out))
    print('written: %d origins' % len(bu.ORIGINS))


if __name__ == '__main__':
    main()
