# -*- coding: utf-8 -*-
"""Build-depth classification of every delivered TESTAHIL valuation study.

One row per covered stock (90 equities in assets/data.js TICKERS; the four metals
studies are excluded - they have no corporate revenue build). Each row records how
the FUNDAMENTAL forecast was actually constructed, read out of the delivered study
itself (and, for the 22 code-built studies, out of engine/<name>_study/compute.py).

TIERS - the standard is SIGCM clause 2 / DRIVER DISCIPLINE in the Standing Research
Protocol: "revenue as VOLUME x PRICE and cost as COST-PER-UNIT ... where unit/segment
data isn't disclosed, drop to the finest sourced level and FLAG the gap."

  A  BOTTOM-UP, DISCLOSED UNITS  - revenue = a disclosed physical unit x a price/rate,
                                   cost per unit, margins as OUTPUTS.
  A- BOTTOM-UP, PART OF REVENUE  - the unit build covers the major legs; the remainder
                                   is segment/growth-level because nothing finer is
                                   disclosed, and the gap is stated in the study.
  B  BOTTOM-UP ON DERIVED UNITS  - a genuine unit-economics model, but the units are
                                   the preparer's estimate, an index, or back-solved
                                   from disclosed totals rather than disclosed.
  C  SEGMENT-LEVEL               - each disclosed segment on its own driver, no unit
                                   economics; gap flagged.
  D  TOP-DOWN                    - group or segment revenue-growth path + a margin
                                   assumption/glide.
  E  ASSET / NAV / STAKE MARKS   - value comes from marking assets, stakes or segment
                                   earnings at multiples; no revenue build at all.
  F  BANK DRIVER BUILD           - balances x margin (NIM/CoR/CIR bridge). The house's
                                   own bank reference study (ADCB) labels this
                                   TOP-DOWN because no product unit economics are
                                   disclosed; kept as its own tier for fairness.

BOTTOM_UP = True only for A / A- / B (a real unit-economics build). Everything else
is False.
"""

# (ticker, company, exchange code, study edition, tier, bottom_up, evidence)
ROWS = [
# ---------------- A : bottom-up on disclosed units ----------------
("ADNOCLS","ADNOC Logistics & Services plc","ADX:ADNOCLS","09-08-2026","A",True,
 "Seven disclosed units, each on its own physical driver; tankers literally vessel by vessel - 12 chartered vessels at their own disclosed rates for the days their contracts run, the other 40 at a market rate solved out of the company's published class averages; gas carriers on contracted vessel-years x day rate; running cost USD 9,164 a vessel-day."),
("ADNOCDIST","Abu Dhabi National Oil Company for Distribution (ADNOC Distribution)","ADX:ADNOCDIST","09-08-2026","A",True,
 "Litres x margin per litre for retail fuel and commercial fuel; non-fuel retail on revenue x gross margin. 'No segment is grown on a blended rate.' Gross margin is shown last, as an OUTPUT."),
("ADNOCDRILL","ADNOC Drilling Company P.J.S.C.","ADX:ADNOCDRILL","09-08-2026","A",True,
 "Rigs in service x revenue per rig-year, by class; rates are arithmetic off disclosed segment revenue and disclosed rig counts. Oilfield services carries TWO disclosed rig populations after a one-driver build implied a negative rate. Margins fall out of a cost stack."),
("AIRARABIA","Air Arabia PJSC","DFM:AIRARABIA","09-08-2026","A",True,
 "Passengers x per-passenger rates (fare+baggage, ancillary, fuel = intensity x jet price, staff). Seats/ASK are not disclosed, so passengers is stated as the finest disclosed level. Margins are OUTPUTS."),
("AMR","Americana Restaurants International PLC","ADX:AMR","09-08-2026","A",True,
 "Restaurants x revenue per restaurant across seven market units; estate grows on the company's own net-new-store programme, revenue per restaurant on disclosed like-for-like, less a currency drag in the unpegged markets. Build reproduces reported revenue in all three audited years."),
("BOROUGE","Borouge plc","ADX:BOROUGE","17-08-2026","A",True,
 "Nameplate capacity x disclosed utilisation for volume; published benchmark + disclosed premium x a measured realisation residual for price; cost in dollars per tonne split by what physically drives it, one escalator per driver class. Capex is flagged as the one materially top-down driver."),
("EMPOWER","Emirates Central Cooling Systems Corporation PJSC","DFM:EMPOWER","09-08-2026","A",True,
 "Two-leg unit build: connected refrigeration tons x the capacity rate, plus consumption per connected ton x the connected base. Volume driver is disclosed connected capacity plus the 311k RT contracted backlog. Margins as OUTPUTS."),
("FERTIGLB","Fertiglobe plc","ADX:FERTIGLB","09-08-2026","A",True,
 "Installed capacity x utilisation by plant and product; realised price = published benchmark x a measured realisation ratio; cash cost per tonne calibrated against disclosed segment economics and cross-checked on gas intensity. The third-party trading leg is the one leg not built from unit economics and the study flags it."),
("SALIK","Salik Company","DFM:SALIK","11-07-2026","A",True,
 "Peak trips x AED 6 plus off-peak trips x AED 4, from the company's own Q1-2026 disclosure; the rebuild reproduces reported toll revenue to five hundredths of one per cent - the study publishes that as an 'audit receipt' before setting any forward driver."),
("LULU","Lulu Retail Holdings","ADX:LULU","13-07-2026","A",True,
 "Six country models driven by stores, retail space (m sqm) and sales density (US$ per sqm); operating cost tracks space x mature-store cost inflation, so the EBITDA margin is a derived break-even, not an input."),
("AMOC","Alexandria Mineral Oils","EGX:AMOC","08-08-2026","A",True,
 "Eight disclosed product lines, tonnes x realisation from note 14-A, rolled on a volume path per line. Cost built PER LINE in two legs - conversion allocated on processing-intensity weights, feedstock on net realisable value - giving a spread per tonne for every line."),
("ARCC","Arabian Cement","EGX:ARCC","08-08-2026","A",True,
 "Tonnes are DISCLOSED (FY2025 investor presentation) and reproduced to within 0.02%. Drivers are physical - kiln utilisation, clinker factor, two export shares - and all three realised prices are OUTPUTS. Three earlier editions that back-solved tonnes from an assumed price were withdrawn as circular."),
("SCEM","Sinai Cement Company S.A.E.","EGX:SCEM","06-08-2026","A",True,
 "Clinker and cement tonnes on kiln/mill utilisation and the clinker factor, split domestic vs export, priced per tonne; variable cost stacked per tonne across fuel, power, raw materials, packaging and distribution (bottom_up.json in the study directory)."),
("EGCH","Egyptian Chemical Industries (KIMA)","EGX:EGCH","08-08-2026","A",True,
 "One reported segment, so the build goes BELOW it to product and channel: tonnes x price channel by channel, cost as physical consumption x a unit price. 'Nothing in the model sets a margin.'"),
("PHAR","Egyptian International Pharmaceutical Industries (EIPICO)","EGX:PHAR","09-08-2026","A",True,
 "Three product lines, each with its own volume and price: 351.8m packs of own preparations split into export (60m at USD 1.00/pack) and domestic (291.8m at EGP 21.22/pack), plus contract manufacturing at EGP 9.00 a pack. The two disclosure splits are reconciled to the thousand pound."),
("SAVOLA","Savola Group Company","TADAWUL:2050","19-08-2026","A-",True,
 "Oil, sugar and pasta are true unit builds on DISCLOSED volumes with gross profit per tonne; Panda is stores x sales per average store. Nuts & spices and the two small legs run on category revenue paths - the study says so in the driver table. Group EBITDA margin is an OUTPUT."),
("DU","Emirates Integrated Telecommunications Company PJSC","DFM:DU","17-08-2026","A-",True,
 "Mobile and Fixed built as volume x price - quarterly customer base x blended ARPU, reproducing the audited FY2025 mobile segment to within 0.1% - with a genuine per-subscriber direct-cost stack (interconnect, capacity, commission). Wholesale and ICT grow on their own revenue because no volume unit is disclosed; stated."),
("CLHO","Cleopatra Hospitals Group","EGX:CLHO","13-07-2026","A-",True,
 "Five disclosed KPI lines, 59% of FY25 revenue, modelled as volume x average revenue per unit and faded from their own FY24-25 growth. The remaining ~41% (pharmacy, lab, IVF) has no disclosed volume/price split and grows top-down off bed capacity - the study cites the data-discipline gate for refusing to manufacture one."),
("DSCW","Dice For Ready-Made Garments","EGX:DSCW","19-07-2026","A-",True,
 "Export book (~65% of revenue) on pieces x USD price - 21.6m pieces at US$4.41 in FY25, tagged 'bottom-up (disclosed)' in the sourcing gate. Retail and the third-party dyeing/printing books run on growth rates."),
("GBCO","GB Corp (Ghabbour)","EGX:GBCO","08-07-2026","A-",True,
 "The Auto leg - the DCF engine of the SOTP - is built on disclosed units x ASP per line of business ('volumes and revenue are published per LoB, so ASP is arithmetic'). GB Capital is marked on adjusted-ROAE book and the associates on a transaction mark, as their class requires."),
# ---------------- B : unit economics on derived / estimated units ----------------
("ELEC","Electro Cable Egypt","EGX:ELEC","05-08-2026","B",True,
 "Revenue = tonnes shipped x price per tonne (LME copper x EGP/USD x a 1.387x fabrication uplift), EBITDA = tonnes x conversion EBITDA per tonne. But 'the company discloses no volumes', so the tonnage is back-solved and validated against the stated ~25,000 t/yr capacity; utilisation is called indicative."),
("RIYADHCABLE","Riyadh Cables Group Company","TADAWUL:4142","18-08-2026","B",True,
 "Cables & wires (98% of revenue) is modelled as a metal converter on a cable-tonnage INDEX (FY2025 = 100): metal content per unit on its own copper/aluminium path, conversion cost per unit on domestic inflation, plus a conversion spread. 'The company does not disclose tonnage, so this is an index, not an absolute volume.' The two small legs carry disclosed segment margins."),
("PHDC","Palm Hills Developments","EGX:PHDC","11-06-2026","B",True,
 "Clean-sheet project-by-project build: every project from its unit mix (apartments, town/twin houses, villas, chalets) priced per square metre, construction and land costed per square metre, only the unsold remainder valued. Project-level inputs are the preparer's estimates."),
("TMGH","Talaat Moustafa Group Holding","EGX:TMGH","17-06-2026","B",True,
 "Development leg built project by project from units x price/m2 and m2 x construction-cost/m2, self-liquidating with no perpetuity; hotels and recurring income are separate EBITDA-multiple segments. Project inputs are estimates calibrated to disclosed totals."),
("OCDI","Sixth of October Development & Investment","EGX:OCDI","24-06-2026","B",True,
 "Every development project from a derived unit mix (units x price/m2) and a derived cost stack (m2 x construction-cost/m2), unsold remainder only, execution-weighted. The study states plainly: 'No project-level data is disclosed by the company ... illustrative, not authoritative.'"),
("ORHD","Orascom Development Egypt","EGX:ORHD","25-06-2026","B",True,
 "Same construction as SODIC - each destination from a derived unit mix x price/m2 and a derived construction cost per m2, unsold remainder only, execution-weighted, calibrated to disclosed FY2025 totals and flagged as derived."),
("EMFD","Emaar Misr for Development","EGX:EMFD","17-06-2026","B",True,
 "Project-by-project bottom-up build from unit mix priced per square metre with construction and land per square metre; hotels and the retail/commercial base as separate EBITDA-multiple segments. Unit mixes and prices are the author's estimates calibrated to disclosed FY2025 totals."),
# ---------------- C : segment-level, no unit economics ----------------
("MODON","Modon Holding PSC","ADX:MODON","10-08-2026","C",False,
 "Each leg on its own driver - development on disclosed backlog conversion plus new launches, the rest anchored on H1 actuals - but the study states it outright: 'Per-project volumes and prices are not disclosed; the build stops at segment level with unit-level anchors ... That gap is flagged, not papered over.'"),
("SWDY","Elsewedy Electric","EGX:SWDY","05-08-2026","C",False,
 "Three disclosed reportable segments, each grown and margined on its own driver, reconciling exactly to audited revenue. But: 'None of the three audited filings ... discloses a tonnage, unit-volume or order-book figure for any segment, so the forecast is built as a taper on each segment's own recent revenue growth and margin path rather than a reconstructed unit model.'"),
("ALDAR","Aldar Properties PJSC","ADX:ALDAR","08-07-2026","C",False,
 "Split-leg SOTP: the development leg is a finite DCF off the disclosed AED 71.7bn backlog and a fading launch programme (backlog conversion, not units x price); Aldar Investment is carried at its stated AED 52bn recurring GAV on an implied cap rate."),
("EMAARDEV","Emaar Development PJSC","DFM:EMAARDEV","08-07-2026","C",False,
 "Split-NAV off the balance sheet: net cash plus the PV of profit still to be recognised on the secured sales backlog (125,200 x a 35% sustainable margin) plus a heavily haircut land-bank value, less central overhead. Backlog-and-margin, not a unit mix."),
("DEWA","DEWA (Dubai Electricity and Water Authority)","DFM:DEWA","11-07-2026","C",False,
 "Driver table carries revenue as a growth rate (7.5% fading to 4.5%) that the study labels 'bottom-up: customer growth + demand/peak trends + Empower consolidation' - a driver-informed growth path, not a tariff x units build. D&A and finance cost are tagged top-down."),
("PRDC","Pioneers Properties for Urban Development","EGX:PRDC","06-07-2026","C",False,
 "Split-leg SOTP: development leg an RNAV off contracted backlog and the launched/unlaunched pipeline with no terminal value; contracting on normalised earnings x a contractor multiple; rental on NOI and a cap rate."),
# ---------------- D : top-down ----------------
("STC","stc Group (Saudi Telecom)","TADAWUL:7010","09-07-2026","D",False,
 "States it explicitly: 'the revenue engine is the section 1.6 segment build (top-down: stc discloses unit revenue, not subscriber x ARPU detail, so per the house data-discipline gate we forecast disclosed segment lines rather than manufacture a bottom-up split)'. Group revenue compounds ~3.0%; EBITDA margin glides."),
("ADNOCGAS","ADNOC Gas","ADX:ADNOCGAS","04-07-2026","D",False,
 "'ADNOC Gas does not disclose per-segment volume x price in the granularity a full bottom-up build would require, so - per the data-discipline gate - we forecast top-down on disclosed margins and split the revenue illustratively 60/40.'"),
("AGTHIA","Agthia Group PJSC","ADX:AGTHIA","06-07-2026","D",False,
 "'Agthia discloses segment revenue and EBITDA but not volume/price splits by pack or SKU, so all forecasts here are top-down normalized margins on the disclosed segment averages; no packs-x-price build is manufactured.'"),
("RMDA","Rameda Pharmaceuticals","EGX:RMDA","13-07-2026","D",False,
 "'The five-year explicit forecast is driven top-down (the data-discipline guard: unit volumes and ASPs by product are not separately disclosed, so channel growth x normalized margins is the honest build).'"),
("SABIC","Saudi Basic Industries Corp","TADAWUL:2010","07-07-2026","D",False,
 "'SABIC does not disclose clean segment-EBITDA splits, so per the data-discipline gate we frame the mix top-down rather than manufacture segment margins.' Revenue fades 2.0-3.5%; EBITDA margin lifted from 15.5% to 19.0%."),
("EAND","e& (Emirates Telecommunications Group)","ADX:EAND","10-07-2026","D",False,
 "Revenue steps +8.5% in FY26E on guidance and settles to 3.0-3.5%; EBITDA margin glides 42.4% to 43.6%. The sourcing gate is explicit that drivers are 'top-down, and flagged as such' wherever no disclosed unit figure was found."),
("BURJEEL","Burjeel Holdings PLC","ADX:BURJEEL","11-07-2026","D",False,
 "Revenue +11% fading to +8% against the guidance record; the modelled EBITDA-margin glide from 19.3% to 22.0% is named as the study's central judgment. No bed/case/occupancy unit build."),
("ARAMCO","Saudi Aramco","TADAWUL:2222","01-07-2026","D",False,
 "Revenue growth tracks an oil-price deck grinding from $70 to a $72-74 mid-cycle; EBIT margins held near 44-45%; capex ~$52-54bn. The reserves-NAV lens marks 247.2bn boe at ~$7/boe - an asset mark, not a production x price build."),
("ACWA","ACWA Power Company","TADAWUL:2082","05-07-2026","E",False,
 "SOTP/NAV on marks: operating portfolio at the capitalised value of distributions (cross-checked on EV per MW), the under-construction book at invested equity plus a development uplift, the pipeline as risk-weighted option value, NOMAC on a fee-stream DCF."),
("MAADEN","Saudi Arabian Mining Company (Ma'aden)","TADAWUL:1211","05-07-2026","E",False,
 "SOTP by commodity segment: each business marked on a normalized near-forward EBITDA and a peer-plus EV/EBITDA multiple, less consolidated net debt. No tonnes x price build."),
("ELM","Elm Company","TADAWUL:7203","10-07-2026","D",False,
 "DCF with a segment scorecard whose BPO and Professional Services splits are 'estimated from disclosed growth rates and the Digital Business figure' - segment revenue paths, no unit economics."),
("EXTRA","United Electronics Company (eXtra)","TADAWUL:4003","10-07-2026","D",False,
 "Split-legs SOTP - retail on an operating-co DCF, Tasheel on its equity book. 'Segment split partly estimated where not separately disclosed (flagged in the driver ledger).' No stores x basket or unit build."),
("AAPL","Apple Inc.","NASDAQ:AAPL","06-07-2026","D",False,
 "Group revenue taken from $442bn to $540bn 'as Services compounds low-double-digits and hardware grows low-single-digits', with the operating margin lifted 32.5% to 34.5%. The segment SOTP marks Services and Products on EV/EBIT multiples."),
("NVDA","NVIDIA Corporation","NASDAQ:NVDA","06-07-2026","D",False,
 "Data Center revenue is a growth fade - '~73% (FY27E) toward ~9% (FY31E)' - driven off aggregate hyperscaler AI capex. No GPU units x ASP build."),
("TSLA","Tesla, Inc.","NASDAQ:TSLA","30-06-2026","E",False,
 "Segment SOTP on multiples: automotive at ~15x normalized EBIT, energy on a growth multiple, services at a modest multiple, plus a probability-weighted autonomy/AI bucket. No deliveries x ASP build."),
("INFY","Infosys Limited","NSE:INFY","06-07-2026","D",False,
 "Revenue compounds 5-7% through the window with the operating margin held in the guided 21-22% band. The vertical/geography section is a scorecard, not a driver build."),
("RELIANCE","Reliance Industries Limited","NSE:RELIANCE","06-07-2026","E",False,
 "Holdco SOTP: Jio at 13.5x EV/EBITDA, Retail at 28x, O2C at 7x, E&P at 5x, Media at 14x, New Energy at invested capital plus option value, less net debt, minorities and a holdco discount."),
("TMPV","Tata Motors Passenger Vehicles Ltd.","NSE:TMPV","30-06-2026","E",False,
 "Holdco SOTP: JLR on normalized mid-cycle EBITDA x a luxury-auto multiple, India PV-ICE on a domestic EV/EBITDA, India EV on a haircut to the TPG/ADIA private round, plus a conglomerate discount."),
("SAMSUNG","Samsung Electronics Co., Ltd.","KRX:005930","27-06-2026","E",False,
 "SOTP on normalised segment operating profit x multiples - memory credited a ~KRW 175tn AI-era plateau capitalised at 9x, the rest marked segment by segment. No wafer/unit build."),
("KAKAO","Kakao Corp.","KRX:035720","28-06-2026","E",False,
 "Holdco SOTP: listed stakes at market, the two large unlisted subsidiaries at transaction marks, the core KakaoTalk platform on a mark, parent net cash, then a 32% NAV discount. The discount is the whole valuation."),
("LGES","LG Energy Solution, Ltd.","KRX:373220","28-06-2026","D",False,
 "Consolidated FCFF with revenue recovering '+17% in 2026e on guidance, easing to +9% by 2030e' and the operating margin climbing from ~6% to 12-13%. GWh appears only in the EV-per-GWh replacement cross-check, not in the forecast."),
("QGTS","Nakilat","QSE:QGTS","05-07-2026","D",False,
 "Charter hire grows in the low-single digits on contract escalators and a handful of deliveries; EBITDA margin held near 71%. Fleet-anchored, but not a vessel-by-vessel day-rate build."),
("IQCD","Industries Qatar","QSE:IQCD","05-07-2026","E",False,
 "Holdco SOTP: each of fertilizers, petrochemicals and steel valued on normalized mid-cycle earnings and a justified P/E, plus net cash, less a holdco discount."),
("EGAL","Egypt Aluminum","EGX:EGAL","03-07-2026","D",False,
 "The primary DCF is built from revenue growth, gross margin, capex and working-capital drivers - anchored on the company's own EGP 11.1bn budget direction then ~10% nominal growth. LME x FX x volume appears only in the normalised-earnings expert lens."),
("EFID","Edita Food Industries","EGX:EFID","03-07-2026","D",False,
 "Revenue growth starts at 30% for FY2026 and fades to 13% by FY2030; EBITDA margin held at 19.2-19.5%. The segment table applies per-segment growth and margin assumptions."),
("EFIH","e-finance for Digital & Financial Investments","EGX:EFIH","03-07-2026","D",False,
 "Revenue growth fades from ~32% toward the low teens with the EBITDA margin held near 50%. The segment SOTP marks each part on FY2025 segment EBITDA x a multiple."),
("JUFO","Juhayna Food Industries","EGX:JUFO","01-07-2026","D",False,
 "FCFF on a group growth-and-margin path; the segment sum is a cross-check that marks each segment's FY25 revenue at a normalized operating margin and an EV/EBIT multiple. No litres or tonnes."),
("LCSW","Lecico Egypt (S.A.E.)","EGX:LCSW","06-07-2026","D",False,
 "Revenue grows 10-13% a year (nominal inflation plus modest export volume) with the EBITDA margin recovering from 12.6% to ~14.5%. Segment detail is used descriptively - 'we use it directly rather than manufacture splits'."),
("ORWE","Oriental Weavers","EGX:ORWE","01-07-2026","D",False,
 "FCFE off attributable profit with the working-capital drag as the crux; the segment section describes export/Egypt-retail/tufted/US-plant mix but the forecast is a growth-and-margin path, not m2 x price."),
("ISPH","Ibnsina Pharma","EGX:ISPH","07-07-2026","D",False,
 "Revenue growth fades from the re-pricing-driven ~20% toward ~11%; EBITDA margin expands 5.1% to 5.5% on scale. Channels are a scorecard, not a driver build."),
("FWRY","Fawry","EGX:FWRY","01-07-2026","D",False,
 "FY26E built on 30% revenue growth and a 56% EBITDA margin, fading 20% to 12% over five years. The segment table shows where growth lives; there is no transactions x take-rate build."),
("ORAS","Orascom Construction","EGX:ORAS","30-06-2026","D",False,
 "'We grow the base at 8% through an explicit five-year window, fade to a 3.5% terminal' on normalized operating profit, with a normalized working-capital drag. Backlog is context, not the driver."),
("ABUK","Abu Kir Fertilizers","EGX:ABUK","01-07-2026","D",False,
 "Operating leg valued on a five-year FCFF with a NORMALIZING EBIT MARGIN (38% to 40%) as the input, then combined with investments and net cash in a three-part SOTP. Margin as an input is the opposite of the cost-per-unit rule."),
("ETEL","Telecom Egypt","EGX:ETEL","03-07-2026","E",False,
 "SOTP: the core marked on 2026E EBITDA of EGP 52.6bn at 3.25x EV/EBITDA, the 45% Vodafone Egypt stake marked on earnings at 8.0x and cross-checked against the 2022 Vodacom transaction."),
("HELI","Heliopolis Housing","EGX:HELI","03-07-2026","E",False,
 "RNAV of the estate block by block: the two JDAs with disclosed economics at the PV of their contractual minimum guarantees, the undisclosed JDAs at EGP 9mn per feddan, unallocated plots at a cash EGP 8mn/fd. Land marks, not a development revenue build."),
("KABO","El Nasr Clothing & Textiles (Kabo)","EGX:KABO","06-07-2026","E",False,
 "RNAV off audited net assets plus a flagged land-and-buildings re-mark and a conservative brand value, less working-capital haircuts. 'KABO does not disclose an asset register'."),
("OIH","Orascom Investment Holding","EGX:OIH","03-07-2026","E",False,
 "Holding-company NAV: ten marks each with its basis - cash, DPRK cash at 50% recovery, the Koryolink loan near face, the Pyramids platform as a standalone DCF - less a 15% holdco discount."),
("CCAP","Qalaa Holdings","EGX:CCAP","30-06-2026","E",False,
 "Holdco SOTP on economic interest: ERC at Qalaa's 13.14% economic stake net of ERC debt, TAQA Arabia at ~55% associate economics, the rest marked. 'The crux that remains is the discount, not the assets.'"),
("HRHO","EFG Holding","EGX:HRHO","01-07-2026","E",False,
 "Holdco SOTP: the Investment Bank at 8x normalized profit, the NBFI platform anchored on the listed Valu stake, Bank NXT's group share at ~5.6x, holdco treasury at book, less a 20% holdco discount."),
("RAYA","Raya Holding","EGX:RAYA","01-07-2026","E",False,
 "Eleven operating companies each marked on an instrument-appropriate basis - Aman on a P/E, RACC at the August-2025 tender price, the rest on EV/EBITDA by business type - less a holdco discount."),
("EMAAR","Emaar Properties PJSC","DFM:EMAAR","01-07-2026","E",False,
 "RNAV/SOTP on marks: listed stakes at market, the recurring mall/hospitality portfolio at ~14x EBITDA, international development and parent net cash, less a 20% NAV/conglomerate discount."),
("IHC","International Holding Company","ADX:IHC","04-07-2026","E",False,
 "Look-through SOTP at spot: the ~60% of Alpha Dhabi at Alpha Dhabi's own ADX market cap, other listed stakes look-through, the unlisted platforms (IRH, RIQ, the private tail) on book or a flagged house estimate."),
("ALPHADHABI","Alpha Dhabi Holding","ADX:ALPHADHABI","10-07-2026","E",False,
 "SOTP NAV: audited FY2025 book equity with the five externally priceable assets re-marked (two at ADX prices, Trojan at the ADQ transaction, dual-framed) and everything else at book. Drivers are a revenue-growth path and a margin."),
("2POINTZERO","Two Point Zero Group","ADX:2POINTZERO","11-07-2026","E",False,
 "Starts from audited owners' equity of AED 83.9bn and does three jobs: re-mark the operating businesses, discount the unlisted portfolio, discount the wrapper. The operating leg is revenue x a disclosed 30% gross margin less 18% admin costs."),
("ADCB","Abu Dhabi Commercial Bank","ADX:ADCB","10-07-2026","F",False,
 "The house's bank reference study, and unusually blunt: 'All eight of ADCB's drivers are top-down, because the bank reports blended results - net interest margin, cost-to-income, cost of risk - rather than the deposit-repricing betas, fee volumes or product unit-economics a bottom-up build would need.'"),
("ADIBUAE","Abu Dhabi Islamic Bank","ADX:ADIB","11-07-2026","F",False,
 "'All of ADIB's drivers are top-down, for a specific and checkable reason: the bank reports blended results ... rather than the deposit-repricing betas, fee volumes or product unit economics a bottom-up build would need.' The negative searches are logged."),
("DIB","Dubai Islamic Bank","DFM:DIB","11-07-2026","F",False,
 "'DIB does not [disclose the components]: it reports blended outcomes - a net profit margin, a cost-to-income ratio, a cost of risk ... So every driver here is set top-down from the outcomes the bank does report.'"),
("ADIB","ADIB-Egypt","EGX:ADIB","03-07-2026","F",False,
 "Attributable earnings from a driver-built income statement: revenue growth fading from +31% to +13.5%, financing growth +53% to +15%, cost-to-income drifting to 20%, cost of risk ~1.0-1.1%. Blended bank metrics, no product unit economics."),
("ALRAJHI","Al Rajhi Bank","TADAWUL:1120","02-07-2026","F",False,
 "Net income from a NIM bridge, a fee line, cost-to-income and cost of risk, feeding a DuPont decomposition and a capital schedule. The study calls this 'a legitimate bottom-up build' because the components are disclosed - the same structure ADCB later labels top-down."),
("ALINMA","Alinma Bank","TADAWUL:1150","10-07-2026","F",False,
 "Three linked schedules - the margin engine (volumes x NIM), the efficiency and risk lines, and the capital the growth consumes. Financing volumes x margin, not product unit economics."),
("RIBL","Riyad Bank","TADAWUL:1010","09-07-2026","F",False,
 "Net income from a NIM path, a fee line, cost-to-income and cost of risk with a DuPont and capital schedule. 'FY23-25 are disclosed; the forward path is the house view.'"),
("SNB","The Saudi National Bank","TADAWUL:1180","04-07-2026","F",False,
 "'We forecast net special commission income as NIM x average earning assets rather than a top-down growth rate', with a DuPont decomposition and an explicit forward capital schedule."),
("COMI","Commercial International Bank","EGX:COMI","29-06-2026","F",False,
 "Justified price-to-book / residual income on a sustainable ROE of 29.5% against a nominal cost of equity - '(29.5-16)/(24-16) = 1.69x'. The driver section is a qualitative scorecard of the sovereign-carry book and the deposit franchise."),
("ENBD","Emirates NBD Bank","DFM:EMIRATESNBD","03-07-2026","F",False,
 "Residual income: (ROTE - Ke) x opening tangible book with ROTE fading from ~19% to a sustainable ~15.5% and book compounding at the retained portion of earnings."),
("FAB","First Abu Dhabi Bank","ADX:FAB","03-07-2026","F",False,
 "Five years of dividends plus a terminal book x a justified P/B from the residual-income identity (ROE - g)/(Ke - g) on a sustainable terminal ROE of 15.5%."),
("QNB","QNB Group","QSE:QNBK","05-07-2026","F",False,
 "FY25 EPS of QAR 1.74 grown at 4% then re-accelerating to 5-7%, payout rising 43% to 47%, terminal payout 60%. An EPS growth path, not a balance-sheet driver build."),
("BTFH","Beltone Financial Holding","EGX:BTFH","03-07-2026","E",False,
 "Financial-services SOTP: attributable book allocated across four platforms on a stated judgment (the group does not disclose allocated equity) and each bucket marked at a justified price-to-book."),
]
