#!/usr/bin/env python3
"""PHAR — the far-year bands this record actually supports.

[R-FCAL-01] requires years 3-5 to be published as RANGES from this record's own
driver-error distribution, never as points.  [R-FCAL-01 AMENDED 07-09-2026]
requires every published band to declare its BASIS from a closed list
(percentile / span / factor), its COUNT, and its ORIENTATION from the closed pair
(actual_over_forecast / forecast_over_actual) — because a factor of 0.4 and a
factor of 2.5 are each an ordinary thing to read on a page and only the
arithmetic behind them says which is meant.

TWO THINGS THIS RECORD CANNOT DO, SAID HERE RATHER THAN DISCOVERED DOWNSTREAM:

  1. THE BASIS IS A SPAN AND NOT A PERCENTILE, at every cell.  The largest cell
     count is five.  A span over five observations is the range of five numbers;
     calling it a p10-p90 would be the free parameter the promotion rule forbids.

  2. THE SCOPE IS LIGHT, SO HORIZONS FOUR AND FIVE HAVE NO BAND AT ALL.  The run
     tests h = 1..3, so the delivered study's forecast years four and five carry
     NO measured range from this record, and the study says so in those words
     rather than borrowing the three-year band and calling it five.
"""
from __future__ import annotations
import json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import bottom_up as bu, score  # noqa: E402

ORIENTATION = "actual_over_forecast"
ORIENTATION_NOTE = (
    "MULTIPLY A POINT PROJECTION BY THESE TO GET THE OUTTURN RANGE. Each factor is "
    "actual / forecast, so a factor above 1.0 means the outturn came in ABOVE the "
    "projection. On this record almost every factor is above 1.0, which is the "
    "under-forecasting of scale the run measured and not a sign error.")
PERCENTILE_MIN_N = 9


def bands():
    rows = score.cells("baseline")
    out = {}
    for drv in sorted({r["driver"] for r in rows}):
        out[drv] = {}
        for h in bu.HORIZONS:
            es = [r["e"] for r in rows if r["driver"] == drv and r["horizon"] == h]
            if not es:
                continue
            f = sorted(math.exp(-e) for e in es)      # actual / forecast
            n = len(f)
            out[drv][str(h)] = dict(
                n=n,
                basis="percentile" if n >= PERCENTILE_MIN_N else "span",
                basis_note=("the 10th and 90th percentiles of %d observations" % n)
                    if n >= PERCENTILE_MIN_N else
                    ("THE RANGE OF %d OBSERVATIONS. Not a percentile and not called one: "
                     "with fewer than %d cells a percentile would be a number invented "
                     "about a distribution this record cannot see." % (n, PERCENTILE_MIN_N)),
                orientation=ORIENTATION,
                orientation_note=ORIENTATION_NOTE,
                mult_low=f[0], mult_high=f[-1],
                median_mult=f[n // 2] if n % 2 else (f[n // 2 - 1] + f[n // 2]) / 2.0,
                mean_log_err=sum(es) / len(es))
    return out


def build():
    b = bands()
    return dict(
        _="PHAR walk-forward far-year bands. GENERATED by forward.py; never hand-edited.",
        run="PHAR", scope="LIGHT",
        basis_list_closed=["percentile", "span", "factor"],
        orientation_list_closed=["actual_over_forecast", "forecast_over_actual"],
        orientation=ORIENTATION, orientation_note=ORIENTATION_NOTE,
        percentile_minimum_n=PERCENTILE_MIN_N,
        horizons_covered=[1, 2, 3],
        horizons_not_covered=dict(
            h4="NO BAND. The run is LIGHT and tests horizons one to three, so this record "
               "carries no measured error at four years and none is invented.",
            h5="NO BAND, same reason."),
        bands=b)


if __name__ == "__main__":
    r = build()
    json.dump(r, open(os.path.join(HERE, "forward_ranges.json"), "w"), indent=1)
    print("PHAR far-year bands — basis, count and ORIENTATION declared on every cell\n")
    print("orientation: %s\n" % ORIENTATION)
    print("%-16s %3s %3s %8s %8s %8s  %s" % ("driver", "h", "n", "low", "median", "high", "basis"))
    for d, hs in r["bands"].items():
        for h, v in hs.items():
            print("%-16s %3s %3d %8.3f %8.3f %8.3f  %s"
                  % (d, h, v["n"], v["mult_low"], v["median_mult"], v["mult_high"], v["basis"]))
    print("\nhorizons four and five: %s" % r["horizons_not_covered"]["h4"][:60] + "...")
