#!/usr/bin/env python3
"""PHAR — the VALUATION-INPUT BLOCK, per origin [R-FCAL-01 AMENDED 03-09-2026].

A driver panel is not a record a value can be rebuilt from, and the difference
stays invisible until something tries.  This commits, at every origin of this
run and under the same point-in-time discipline as every other figure in it:

    cash and equivalents · interest-bearing debt · PP&E · depreciation and
    amortisation · the working-capital lines · the share count footed against
    the par value · capex, disclosed or DERIVED and labelled as derived.

BUILT AS THE RUN WENT, NOT RETRO-FITTED.  The five runs that predate the
amendment were each opened again afterwards and several of their figures could
no longer be obtained at all.

A MISSING ITEM IS RECORDED AS MISSING, NAMED WITH ITS REASON, NEVER OMITTED —
a block quietly carrying six of seven reads as complete.  Two cells in this run
are missing and both are the same fact: the FY2020 annual report presents its
consolidated cash-flow statement in condensed form, so neither the consolidated
depreciation charge nor consolidated capex exists in any document published by
that origin.  They are NOT taken from the following year's comparative, because
a figure carried back is fabricated in vintage — plausible on the page and
invisible in the pooled error afterwards.

GENERATED by this file from panel.py; never hand-edited.
"""
from __future__ import annotations
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import panel  # noqa: E402

ORIGINS = ["FY2020", "FY2021", "FY2022", "FY2023", "FY2024"]
PRIOR = "FY2019"

ROUTE = ("text layer (PyMuPDF `get_text`), with Arabic-Indic digits normalised to Latin "
         "before any figure was read; EVERY statement footed against its own subtotals "
         "before it was recorded, and where a printed cell does not foot the STATEMENT'S "
         "OWN CHAIN settles it and the defective cell is named in panel.FOOTING_FAILURES. "
         "Arithmetic is the arbiter, not the extractor's confidence.")


def _src(y):
    key = panel.BS[y]["src"]
    f = panel.FILINGS[key]
    return "%s, %s (%s)" % (f["file"], f["what"], f["url"])


def _cash(y):
    b = panel.BS[y]
    return dict(value=b["cash"], as_at="%s-12-31" % y[2:6], source=_src(y) +
                ", consolidated statement of financial position, 'cash and balances at banks'",
                route=ROUTE,
                check="the consolidated cash-flow statement closes on the same figure")


def _debt(y):
    b = panel.BS[y]
    lines = {k: b[k] for k in ("lt_loans", "lt_facilities", "bank_credit") if b.get(k)}
    if b.get("st_loans"):
        lines["st_loans"] = b["st_loans"]
    return dict(value=panel.interest_bearing_debt(y), as_at="%s-12-31" % y[2:6],
                source=_src(y) + ", consolidated statement of financial position: long-term "
                "loans, long-term credit facilities, short-term loans and creditor banks "
                "(bank credit facilities)",
                route=ROUTE, lines=lines,
                basis="INTEREST-BEARING ONLY [R-FCAL-01 trap (i)]. Trade and notes payable, "
                      "other creditors, provisions, income tax payable, dividends payable and "
                      "lease liabilities are EXCLUDED — they bear no interest, and dividing the "
                      "finance charge by a broader total understates the rate by a multiple and "
                      "manufactures a bias that looks exactly like evidence.")


def _ppe(y):
    b = panel.BS[y]
    return dict(value=b["ppe"], as_at="%s-12-31" % y[2:6],
                source=_src(y) + ", consolidated statement of financial position, "
                "'fixed assets (net)'",
                route=ROUTE,
                projects_under_construction=b["cip"],
                note="projects under construction are recorded beside PP&E rather than inside "
                     "it, and on this company they are the larger number from FY2023: the "
                     "EIPICO 3 biologicals plant. A capex or asset-base figure that reads PP&E "
                     "alone here misses most of the programme.")


def _dep(y):
    c = panel.CF[y]
    if c["dep"] is None:
        d = dict(missing=c["missing"])
        later = panel.LATER_DISCLOSURE.get(y)
        if later:
            d["later_disclosure"] = later
        return d
    return dict(value=panel.dna(y), as_at="year ended %s-12-31" % y[2:6],
                source=_src(y) + ", consolidated statement of cash flows: depreciation of "
                "fixed assets, amortisation of right-of-use assets and amortisation of "
                "intangible assets",
                route=ROUTE,
                lines=dict(depreciation=c["dep"], right_of_use=c["rou_amort"],
                           intangibles=c["intang_amort"]))


def _capex(y):
    c = panel.CF[y]
    if c["capex"] is not None:
        return dict(value=c["capex"], as_at="year ended %s-12-31" % y[2:6],
                    source=_src(y) + ", consolidated statement of cash flows, investing "
                    "activities, 'payments to purchase fixed assets'",
                    route=ROUTE, derived=False,
                    note="DISCLOSED. The identity capex = dPPE + D&A is NOT used where the "
                         "cash-flow statement states the figure, and on this company it would "
                         "be badly wrong if it were: spend lands in projects under construction "
                         "for years before it reaches PP&E.")
    d = dict(missing=c["missing"], derived=False)
    later = panel.LATER_DISCLOSURE.get(y)
    if later:
        d["later_disclosure"] = later
    b, p = panel.BS.get(y), panel.BS.get(PRIOR)
    if y == "FY2020" and b and p:
        d["identity_not_available"] = (
            "capex = dppe + d&a cannot be evaluated at this origin either, because the D&A term "
            "is the same missing figure: the consolidated depreciation charge is not disclosed "
            "in this origin's own filing. dPP&E is %d and dPP&E including projects under "
            "construction is %d, both recorded so the arithmetic can be finished the day a "
            "consolidated FY2020 charge is published."
            % (b["ppe"] - p["ppe"], (b["ppe"] + b["cip"]) - (p["ppe"] + p["cip"])))
    return d


def _wc(y):
    b = panel.BS[y]
    lines = dict(inventory=b["inventory"], trade_and_notes_receivable=b["ar"],
                 other_receivables=b["other_rec"], trade_and_notes_payable=b["ap"],
                 other_creditors=b["other_cl"])
    net = (b["inventory"] + b["ar"] + b["other_rec"]) - (b["ap"] + b["other_cl"])
    return dict(value=net, as_at="%s-12-31" % y[2:6],
                source=_src(y) + ", consolidated statement of financial position",
                route=ROUTE, lines=lines,
                definition="inventory + trade and notes receivable + other receivables "
                           "- trade and notes payable - other creditors. Cash, borrowings, "
                           "tax payable, provisions and dividends payable are excluded.")


def _shares(y):
    s = panel.SHARES[y]
    return dict(value=s["count"], issued_capital=s["issued_capital"], par_value=s["par"],
                as_at="%s-12-31" % y[2:6],
                source="%s, paid-in capital note; the nominal value per share of EGP 10 is "
                       "stated in the same report's governance section ('the nominal value per "
                       "share, 10 pounds')" % _src(y),
                route=ROUTE,
                foots="issued capital %d / par %.0f = %d, the count the same document states"
                      % (s["issued_capital"], s["par"], s["count"]),
                note=s.get("note", "TODAY'S COUNT IS NEVER CARRIED BACK. This company raised "
                           "capital twice inside the window, in August 2023 and July 2025, so a "
                           "carried count would be wrong by 50% at the early origins."))


def build():
    rec = dict(
        _="The inputs a VALUE is rebuilt from at each of this run's origins, committed beside "
          "the driver panel under [R-FCAL-01 AMENDED]. GENERATED by "
          "engine/phar_walkforward/valuation_inputs.py, which reads panel.py and foots every "
          "balance sheet against its own subtotals at import; never hand-edited.",
        run="PHAR", rule="[R-FCAL-01 AMENDED] (03-09-2026)",
        company="Egyptian International Pharmaceutical Industries Company (EIPICO)",
        currency="EGP", units="as printed in the filings — units of one pound, except FY2019 "
                              "and FY2020 which the FY2020 report prints in thousands and which "
                              "are carried here multiplied to units, labelled in panel.py",
        basis="consolidated", fiscal_year_end="31 December",
        origins_declared_by="PRE_REGISTRATION_07-09-2026.md",
        route=ROUTE,
        point_in_time="every year is carried AS FIRST REPORTED, from its own annual report's own "
                      "column. The eight re-presentations inside this window are recorded in "
                      "panel.REPRESENTATIONS beside the figures they would replace and are never "
                      "substituted.",
        sources={k: v["file"] for k, v in panel.FILINGS.items()},
        origins={}, prior_year_anchor={},
    )
    for y in ORIGINS:
        rec["origins"][y] = dict(cash=_cash(y), debt=_debt(y), capex=_capex(y), ppe=_ppe(y),
                                 dep=_dep(y), wc=_wc(y), shares=_shares(y))
    rec["prior_year_anchor"][PRIOR] = dict(
        _="the year the trailing window reaches and the run does NOT test. Recorded here rather "
          "than under `origins`, because recording it as an origin would misstate what the run "
          "tested.",
        cash=_cash(PRIOR), debt=_debt(PRIOR), capex=_capex(PRIOR), ppe=_ppe(PRIOR),
        dep=_dep(PRIOR), wc=_wc(PRIOR), shares=_shares(PRIOR))
    return rec


if __name__ == "__main__":
    panel.assert_all()
    r = build()
    with open(os.path.join(HERE, "valuation_inputs.json"), "w", encoding="utf-8") as f:
        json.dump(r, f, indent=1, ensure_ascii=False)
    miss = [(y, k) for y, b in r["origins"].items() for k, v in b.items() if "missing" in v]
    print("valuation-input block written: %d origins, 1 prior-year anchor" % len(r["origins"]))
    for y in ORIGINS:
        b = r["origins"][y]
        print("  %s  cash %13d  debt %13d  wc %13d  shares %9d  capex %s  dep %s"
              % (y, b["cash"]["value"], b["debt"]["value"], b["wc"]["value"],
                 b["shares"]["value"],
                 ("%13d" % b["capex"]["value"]) if "value" in b["capex"] else "      MISSING",
                 ("%12d" % b["dep"]["value"]) if "value" in b["dep"] else "     MISSING"))
    print("  items recorded MISSING with a reason: %d %s" % (len(miss), miss))
