#!/usr/bin/env python3
"""[R-CAL-02] Generate the BANDS block in assets/data.js from the live panels.

Every number here is COMPUTED from engine/panels/*_3m.csv. Nothing is typed.
The block is regenerated on every refit, because a coverage figure moves the
moment a forecast is graded -- which is exactly why the old scheme's hand-written
prose ("the calibration behind the cone is PARITY") went stale and stayed stale.

Run:  python3 scripts/build_band_records.py --write
"""
import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine import band_record as br  # noqa: E402

DATA_JS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "assets", "data.js")
START = "// ---- BANDS ---- [R-CAL-02] GENERATED by scripts/build_band_records.py"
END = "// ---- end BANDS ----"


def ledger_instruments(src: str):
    seg = src[src.index("const LEDGER"):src.index("const BACKTEST")]
    return sorted(set(re.findall(r'instrument:\s*"([^"]+)"', seg)))


def build(src: str):
    records = br.by_key()
    names = ledger_instruments(src)
    resolved, claimed = {}, set()
    for n in names:
        r = br.resolve(n, records)          # raises on an unmapped/ambiguous name
        resolved[n] = r
        claimed.add((r.market, r.instrument))

    # Count against the known total, both ways -- a tool reporting "0 skipped"
    # is not evidence (a regex once silently dropped 2POINTZERO from three tools).
    if len(resolved) != len(names):
        raise AssertionError(f"resolved {len(resolved)} of {len(names)} instruments")
    unclaimed = set(records) - claimed
    if unclaimed:
        raise AssertionError(f"{len(unclaimed)} panels claimed by no ledger name: "
                             f"{sorted(unclaimed)}")
    if len(claimed) != len(records):
        raise AssertionError(f"{len(claimed)} panels claimed, {len(records)} exist")

    lines = [START,
             "// One record per covered name: n = resolved non-overlapping 3-month",
             "// windows, c90 = share of them that finished inside the 90% band,",
             "// strength = long (>=40) / short (>=22) / market-only, flag = narrow |",
             "// wide | null (two-sided binomial vs the 90% target, 5% level).",
             "// Derivation of the thresholds: engine/band_record.py. NEVER hand-edit.",
             "const BANDS = {"]
    for n in names:
        r = resolved[n]
        key = n if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", n) else f'"{n}"'
        cov = "null" if r.cov90 is None else f"{r.cov90:.4f}"
        flag = "null" if r.flag is None else f'"{r.flag}"'
        lines.append(f'  {key}: {{mkt:"{r.market}", n:{r.n}, hits:{r.hits}, '
                     f'c50:{r.cov50:.4f}, c80:{r.cov80:.4f}, c90:{cov}, '
                     f'strength:"{r.strength}", flag:{flag}}},')
    lines.append("};")
    # Pooled market fallback, for the names whose own record is too short to read.
    lines.append("// Pooled per-market record: what a market-only name is judged on.")
    lines.append("const BAND_MARKETS = {")
    for m in sorted({r.market for r in resolved.values()}):
        mr = br.market_record(m)
        lines.append(f'  {m}: {{names:{mr["names"]}, n:{mr["n"]}, '
                     f'c90:{mr["cov90"]:.4f}}},')
    lines.append("};")
    lines.append(END)
    return "\n".join(lines), resolved


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    src = open(DATA_JS, encoding="utf-8").read()
    block, resolved = build(src)

    if START in src:
        i, j = src.index(START), src.index(END) + len(END)
        out = src[:i] + block + src[j:]
    else:
        anchor = "const LEDGER = ["
        i = src.index(anchor)
        out = src[:i] + block + "\n\n" + src[i:]

    flagged = [(n, r) for n, r in resolved.items() if r.flag]
    strengths = {}
    for r in resolved.values():
        strengths[r.strength] = strengths.get(r.strength, 0) + 1
    print(f"{len(resolved)} names — " +
          ", ".join(f"{k}: {v}" for k, v in sorted(strengths.items())))
    for n, r in sorted(flagged, key=lambda x: x[1].flag or ""):
        print(f"  {r.flag.upper():6s} {n:12s} {r.chip()}")
    if a.write:
        open(DATA_JS, "w", encoding="utf-8").write(out)
        print(f"\nwrote {DATA_JS}")
    else:
        print("\n(dry run — pass --write)")


if __name__ == "__main__":
    main()
