"""PRICES — the freshest price this repository HOLDS for each covered name, dated.

WHY THIS BLOCK EXISTS. Every price surface on the site reads TICKERS[k].spot,
which is the price a cone was STRUCK at. That is the right number for the forecast
and the wrong number for a gap: [R-GAP-01] measures a fair value against the
LATEST KNOWN price, and on the day this was written eleven EGX strikes were four
to six weeks behind the prices actually held, one name by 273%. A screener ranking
on the strike price ranks a name on a comparison nobody can act on.

IT DOES NOT PRETEND TO BE LIVE, AND THAT IS THE DESIGN. Prices are entered by hand,
so they arrive with lags and gaps; the honest response is not a freshness gate that
nobody can clear but a DATE printed beside every number, the same discipline the
two-part as-of stamps and the library-staleness advisory already follow — staleness
is a data-supply fact, disclosed, never a blocker.

GENERATED, NEVER HAND-EDITED. A page that states a fact which moves must not be the
thing that remembers it [R-CAL-02]. Re-run this in the same pass as any price
supply, refit, roll-forward or study re-issue; scripts/check_prices_block.py holds
the committed block against what these same readers produce now, and goes red when
they disagree.

TWO SOURCES, NEWEST WINS, BOTH NAMED: the supplied price files (merged across all
of them by engine/prices/gap_today.latest_price_per_ticker, because one file is not
the state of the book) and each name's own OHLC library. A name resolving to
neither is REPORTED, never dropped [R-ENF-04].
"""
from __future__ import annotations

import csv
import io
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "engine"))
sys.path.insert(0, os.path.join(ROOT, "engine", "prices"))
import instrument_map as IM                                       # noqa: E402
import gap_today as GT                                            # noqa: E402

DATA_JS = os.path.join(ROOT, "assets", "data.js")
LEGACY_JS = os.path.join(ROOT, "legacy", "assets", "data.js")
MARK_A = "// ==== PRICES (generated by scripts/build_prices_block.py — do not hand-edit) ===="
MARK_B = "// ==== END PRICES ===="


def tickers_index():
    """(key, code) for every TICKERS entry, read by LOADING data.js in node.

    Parsed with the real parser rather than a regex: a JavaScript object literal
    takes the LAST duplicate key and re.search takes the first [R-ENF-03].
    """
    out = subprocess.run(
        ["node", "-e",
         "const fs=require('fs'),vm=require('vm');"
         "let s=fs.readFileSync(process.argv[1],'utf8');"
         "s+='\\n;globalThis.__T=TICKERS;';const c={window:{}};"
         "vm.createContext(c);vm.runInContext(s,c);"
         "console.log(JSON.stringify(Object.entries(c.__T).map(([k,v])=>[k,v.code])));",
         DATA_JS],
        capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def library_close(path):
    """(iso_date, close) of the newest row, or (None, None)."""
    best = None
    with io.open(path, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            d = (row.get("Date") or "").strip().strip('"')
            try:
                m, dd, y = d.split("/")
                iso = "%s-%02d-%02d" % (y, int(m), int(dd))
                px = float((row.get("Price") or "").replace(",", ""))
            except Exception:
                continue
            if best is None or iso > best[0]:
                best = (iso, px)
    return best or (None, None)


def build():
    supplied = GT.latest_price_per_ticker()
    rows, unresolved = {}, []
    for key, code in tickers_index():
        cands = []
        s = supplied.get(key) or supplied.get(GT.ALIAS.get(key, key))
        if s:
            cands.append((s["date"], s["price"], s["file"]))
        p = IM.raw_path(key, code)
        if p:
            d, px = library_close(p)
            if d:
                cands.append((d, px, "library"))
        if not cands:
            unresolved.append(key)
            continue
        d, px, src = max(cands, key=lambda c: c[0])
        rows[key] = {"px": round(px, 4), "date": d, "src": src}
    return rows, unresolved


def render(rows):
    body = ",\n".join(
        '  %s: { px: %s, date: "%s", src: "%s" }'
        % (k if k[0].isalpha() else '"%s"' % k, rows[k]["px"], rows[k]["date"], rows[k]["src"])
        for k in sorted(rows))
    return "%s\nconst PRICES = {\n%s\n};\n%s" % (MARK_A, body, MARK_B)


def splice(path, block, mark_a=None, mark_b=None):
    """Replace EVERY existing copy of the block, then insert once.

    A JavaScript file takes the LAST declaration of a `const` and throws on the
    second, so a splice that replaces only the first copy leaves a file that will
    not load. Removing all of them and appending once is the only shape that is
    idempotent however many times it has run before.
    """
    a_mark = mark_a or MARK_A
    b_mark = mark_b or MARK_B
    s = io.open(path, encoding="utf-8").read()
    while a_mark in s and b_mark in s[s.index(a_mark):]:
        a = s.index(a_mark)
        b = s.index(b_mark, a) + len(b_mark)
        s = s[:a].rstrip("\n") + "\n" + s[b:].lstrip("\n")
    s = s.rstrip("\n") + "\n\n" + block + "\n"
    io.open(path, "w", encoding="utf-8").write(s)


def main():
    rows, unresolved = build()
    if not rows:
        raise SystemExit("REFUSED: resolved a price for zero names. An empty "
                         "result is not a clean result [R-ENF-04].")
    block = render(rows)
    splice(DATA_JS, block)
    if os.path.exists(LEGACY_JS):
        splice(LEGACY_JS, block)

    # Verify by LOADING, not by parsing, and count against a known total.
    total = len(tickers_index())
    chk = subprocess.run(
        ["node", "-e",
         "const fs=require('fs'),vm=require('vm');"
         "let s=fs.readFileSync(process.argv[1],'utf8');"
         "s+='\\n;globalThis.__P=PRICES;globalThis.__T=TICKERS;';const c={window:{}};"
         "vm.createContext(c);vm.runInContext(s,c);"
         "const P=c.__P;const bad=Object.entries(P).filter(([k,v])=>!(v&&v.px>0&&v.date&&v.src));"
         "if(bad.length) throw new Error('malformed rows: '+bad.map(b=>b[0]));"
         "console.log(JSON.stringify({priced:Object.keys(P).length,tickers:Object.keys(c.__T).length}));",
         DATA_JS],
        capture_output=True, text=True)
    if chk.returncode != 0:
        raise SystemExit("REFUSED: data.js will not load after the splice.\n" + chk.stderr)
    got = json.loads(chk.stdout)
    print("PRICES written: %d of %d covered names" % (got["priced"], got["tickers"]))
    dates = sorted({r["date"] for r in rows.values()})
    print("  price dates span %s .. %s" % (dates[0], dates[-1]))
    bysrc = {}
    for r in rows.values():
        bysrc[r["src"]] = bysrc.get(r["src"], 0) + 1
    for s, n in sorted(bysrc.items(), key=lambda x: -x[1]):
        print("  %-28s %d" % (s, n))
    if unresolved:
        print("  NO PRICE RESOLVED (named, not dropped): " + ", ".join(sorted(unresolved)))


if __name__ == "__main__":
    main()
