"""SCREEN — where each covered name stops in the selection funnel, and why.

WHAT THIS IS. The funnel is a chain of gates ordered so the decisions with a
track record run before the ones without: inputs, size cap, the fundamental gap,
the momentum veto, three-lens agreement. This block records, per name, the state
each gate reads and the FIRST gate that stops it, so the screener can show the
chain rather than a single ranked column.

EVERY THRESHOLD IN IT IS INHERITED, NONE IS MINTED. The 10% gap trigger is
[R-GAP-01]'s own, both-sided since 02-09-2026. The momentum dead zone 0.25 and
clip 2.5 are the engine's signal socket. The record-strength cuts 22 and 40 are
[R-CAL-02]'s, derived there from power and from the book's own window counts. A
new number chosen here would be a free parameter with no evidence behind it,
which the promotion rule forbids.

THERE IS DELIBERATELY NO STALENESS CUTOFF. How old a library or a price is gets
REPORTED as a date and never decides anything: staleness is a data-supply fact, a
stale library still yields a coherent read, and a rule carrying a threshold
schedules its own staleness. Gate 1 asks only whether the inputs EXIST.

NOT A RATING AND NOT A RECOMMENDATION. It records what the published numbers say
about each name against the rules already written down; the gap lens has no
graded record, which the block states in its own field rather than leaving to the
reader to remember.

GENERATED, NEVER HAND-EDITED — re-run in the same pass as any price supply,
refit, roll-forward or study re-issue. scripts/check_screen_block.py holds it to
what these readers produce now.
"""
from __future__ import annotations

import csv
import datetime as dt
import io
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "engine"))
import build_prices_block as BP                                   # noqa: E402
import instrument_map as IM                                       # noqa: E402
sys.path.insert(0, os.path.join(ROOT, "engine", "prices"))
import gap_today as GT                                            # noqa: E402

DATA_JS = BP.DATA_JS
LEGACY_JS = BP.LEGACY_JS
MARK_A = "// ==== SCREEN (generated by scripts/build_screen_block.py — do not hand-edit) ===="
MARK_B = "// ==== END SCREEN ===="

GAP_TRIGGER = 0.10        # [R-GAP-01], both sides
DEAD_ZONE = 0.25          # engine signal socket
STRONG_Z = 1.00           # |z| at which the measured lean actually paid
SHORT_RECORD = 22         # [R-CAL-02] strength cuts, derived there
LONG_RECORD = 40


def site_state():
    out = subprocess.run(
        ["node", "-e",
         "const fs=require('fs'),vm=require('vm');"
         "let s=fs.readFileSync(process.argv[1],'utf8');"
         "s+='\\n;globalThis.__O={T:TICKERS,B:(typeof BANDS!==\"undefined\")?BANDS:{},"
         "P:(typeof PRICES!==\"undefined\")?PRICES:{}};';const c={window:{}};"
         "vm.createContext(c);vm.runInContext(s,c);"
         "const o=c.__O,out={};"
         "for(const [k,v] of Object.entries(o.T)) out[k]={code:v.code,fair:v.fair||null,"
         "fairAsof:v.fairAsof||null,spot:v.spot,tech:(v.tech&&v.tech.trend)||null,"
         "band:o.B[k]||null,px:o.P[k]||null};"
         "console.log(JSON.stringify(out));",
         DATA_JS],
        capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def series(path):
    rows = []
    with io.open(path, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            d = (r.get("Date") or "").strip().strip('"')
            try:
                m, dd, y = d.split("/")
                rows.append((dt.date(int(y), int(m), int(dd)),
                             float((r.get("Price") or "").replace(",", ""))))
            except Exception:
                continue
    rows.sort()
    return rows


def _on(rows, target):
    c = [r for r in rows if r[0] <= target]
    return c[-1][1] if c else None


def momentum(state):
    """mom_combo z per MARKET panel — the construction the engine tilts on.

    Cross-sectional by market because that is the panel a z means anything
    against; a name whose library cannot reach the anchor is left out and NAMED
    by its absence from the result rather than scored on a shorter window.
    """
    by_mkt = {}
    for k, v in state.items():
        p = IM.raw_path(k, v["code"] or "")
        if not p:
            continue
        by_mkt.setdefault(IM.market_of(v["code"]), {})[k] = series(p)

    out = {}
    for mkt, libs in by_mkt.items():
        anchors = [r[-1][0] for r in libs.values() if r]
        if not anchors:
            continue
        anchor = max(anchors)
        raw = {}
        for k, rows in libs.items():
            if not rows:
                continue
            a = _on(rows, anchor)
            m1 = _on(rows, anchor - dt.timedelta(days=30))
            m6 = _on(rows, anchor - dt.timedelta(days=182))
            m12 = _on(rows, anchor - dt.timedelta(days=365))
            if None in (a, m1, m6, m12) or 0 in (m6, m12):
                continue
            closes = [c for d, c in rows if d <= anchor]
            s200 = sum(closes[-200:]) / 200 if len(closes) >= 200 else None
            s200p = sum(closes[-220:-20]) / 200 if len(closes) >= 220 else None
            raw[k] = dict(m12=m1 / m12 - 1, m6=m1 / m6 - 1,
                          trend=bool(s200 and s200p and a > s200 and s200 > s200p),
                          lib=rows[-1][0].isoformat())
        if len(raw) < 3:                      # a z against two names is noise
            for k, r in raw.items():
                out[k] = dict(z=None, trend=r["trend"], lib=r["lib"], panel=len(raw))
            continue
        for field in ("m12", "m6"):
            vals = [r[field] for r in raw.values()]
            mu = sum(vals) / len(vals)
            sd = (sum((v - mu) ** 2 for v in vals) / (len(vals) - 1)) ** 0.5 or 1.0
            for r in raw.values():
                r["z_" + field] = (r[field] - mu) / sd
        for k, r in raw.items():
            out[k] = dict(z=round(0.5 * r["z_m12"] + 0.5 * r["z_m6"], 3),
                          trend=r["trend"], lib=r["lib"], panel=len(raw))
    return out


def rebuild_pending():
    """Names whose committed study central is no longer the published one.

    THE NUMBER ITSELF IS NOT RECORDED HERE AND THAT IS DELIBERATE. A rebuilt
    central that has not published is HELD [R-GAP-02], and this block ships to
    the public site; what a reader is owed is not the held figure but the fact
    that the published one is superseded, so a name is not presented as a clean
    candidate on a number the house has already moved past. Measured 06-09-2026
    the difference is not cosmetic: one name's published fair value put it 52%
    above the price while its rebuilt central put it 5% below.
    """
    import glob
    out = set()
    for sdir in sorted(glob.glob(os.path.join(ROOT, "engine", "*_study"))):
        tk = os.path.basename(sdir)[:-6].upper()
        try:
            central, _spot, _note = GT.read_study(sdir)
        except Exception:
            continue
        if central:
            out.add(tk)
    return out


def classify(v, mom, pending):
    """The first gate that stops this name, and what each gate read."""
    px = (v["px"] or {}).get("px") or v["spot"]
    pxd = (v["px"] or {}).get("date")
    fair = (v["fair"] or {}).get("base")
    band = v["band"] or {}
    m = mom.get(v["_k"], {})
    z, trend = m.get("z"), m.get("trend")

    row = {"px": px, "pxDate": pxd, "lib": m.get("lib"), "z": z, "trend": trend,
           "fair": fair, "fairAsof": v["fairAsof"], "rebuilt": v["_k"] in pending,
           "n": band.get("n"), "c90": band.get("c90"), "flag": band.get("flag")}

    # GATE 1 — do the inputs exist at all? (age is reported, never gated)
    missing = []
    if not fair:
        missing.append("no fair value")
    if not v["fairAsof"]:
        missing.append("fair value undated")
    if z is None:
        missing.append("momentum not computable")
    if not band.get("n"):
        missing.append("no band record")
    if missing:
        row.update(stop="inputs", why="; ".join(missing))
        return row

    # A published fair value the house has already moved past cannot carry a
    # candidate, whichever way it points.
    if row["rebuilt"]:
        row.update(stop="superseded",
                   why="a rebuilt study supersedes the published fair value and has not published")
        return row

    # GATE 2 — the size cap this name's own record earns
    n = band["n"]
    row["cap"] = ("reduced" if band.get("flag") == "narrow"
                  else "thin record" if n < SHORT_RECORD
                  else "full" if n >= LONG_RECORD else "partial")

    # GATE 3 — the gap, against the latest price we hold
    gap = fair / px - 1 if px else None
    row["gap"] = round(gap, 4) if gap is not None else None
    if gap is None:
        row.update(stop="inputs", why="no price to compare against")
        return row
    if gap <= -GAP_TRIGGER:
        row.update(stop="gap", why="sits more than 10% below the price — audited, not traded")
        return row
    if gap < GAP_TRIGGER:
        row.update(stop="gap", why="inside 10% of the price either way — no candidate")
        return row

    # GATE 4 — the momentum veto
    if z <= -STRONG_Z:
        row.update(stop="momentum", why="strong negative direction call")
        return row

    # GATE 5 — do the three lenses agree?
    lens = []
    if z <= -DEAD_ZONE:
        lens.append("momentum call is down")
    if not trend:
        lens.append("tape is not constructive")
    if lens:
        row.update(stop="lenses", why="; ".join(lens))
        return row

    row.update(stop=None, why="clears every gate on the published numbers")
    return row


def build():
    state = site_state()
    for k, v in state.items():
        v["_k"] = k
    mom = momentum(state)
    pending = rebuild_pending()
    return {k: classify(v, mom, pending) for k, v in state.items()}


def js(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return json.dumps(v)


FIELDS = ["px", "pxDate", "lib", "z", "trend", "gap", "fair", "fairAsof",
          "rebuilt", "n", "c90", "flag", "cap", "stop", "why"]


def render(rows):
    body = ",\n".join(
        "  %s: { %s }" % (k if k[0].isalpha() else '"%s"' % k,
                          ", ".join("%s: %s" % (f, js(rows[k].get(f))) for f in FIELDS))
        for k in sorted(rows))
    return "%s\nconst SCREEN = {\n%s\n};\n%s" % (MARK_A, body, MARK_B)


def main():
    rows = build()
    if not rows:
        raise SystemExit("REFUSED: classified zero names [R-ENF-04].")
    block = render(rows)
    BP.splice(DATA_JS, block, MARK_A, MARK_B)
    if os.path.exists(LEGACY_JS):
        BP.splice(LEGACY_JS, block, MARK_A, MARK_B)
    chk = subprocess.run(
        ["node", "-e",
         "const fs=require('fs'),vm=require('vm');"
         "let s=fs.readFileSync(process.argv[1],'utf8');"
         "s+='\\n;globalThis.__S=SCREEN;globalThis.__T=TICKERS;';const c={window:{}};"
         "vm.createContext(c);vm.runInContext(s,c);"
         "console.log(JSON.stringify({s:Object.keys(c.__S).length,t:Object.keys(c.__T).length}));",
         DATA_JS], capture_output=True, text=True)
    if chk.returncode:
        raise SystemExit("REFUSED: data.js will not load after the splice.\n" + chk.stderr)
    got = json.loads(chk.stdout)
    if got["s"] != got["t"]:
        raise SystemExit("REFUSED: %d screened against %d covered names."
                         % (got["s"], got["t"]))
    tally = {}
    for r in rows.values():
        tally[r["stop"] or "clears"] = tally.get(r["stop"] or "clears", 0) + 1
    print("SCREEN written: %d of %d covered names" % (got["s"], got["t"]))
    for kk in ["inputs", "superseded", "gap", "momentum", "lenses", "clears"]:
        if kk in tally:
            print("  stops at %-9s %3d" % (kk, tally[kk]))
    clear = sorted(k for k, r in rows.items() if r["stop"] is None)
    print("  clears every gate: " + (", ".join(clear) if clear else "(none)"))


if __name__ == "__main__":
    main()
