#!/usr/bin/env python3
"""[R-CAL-02] Generate the BANDS block in assets/data.js from the live panels.

Every number here is COMPUTED from engine/panels/*_3m.csv. Nothing is typed.
The block is regenerated on every refit, because a coverage figure moves the
moment a forecast is graded -- which is exactly why the old scheme's hand-written
prose ("the calibration behind the cone is PARITY") went stale and stayed stale.

Run:  python3 scripts/build_band_records.py --write
"""
import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine import band_record as br  # noqa: E402

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JS = os.path.join(ROOT_DIR, "assets", "data.js")
START = "// ---- BANDS ---- [R-CAL-02] GENERATED by scripts/build_band_records.py"
END = "// ---- end BANDS ----"


def ledger_instruments(_src=None):
    """Names in LEDGER, via the repo's existing node-backed loader.

    NOT a regex over data.js: grade_ledger.py already documents that LEDGER
    carries two literal styles (instrument:"X" and instrument: "X") precisely
    because a regex standing in for a parser has bitten here before, and the
    standing rule is verify-by-load.
    """
    sys.path.insert(0, os.path.join(ROOT_DIR, "engine"))
    from engine.fv_overlay import load_ledger
    return sorted({r["instrument"] for r in load_ledger()})


def build(src: str):
    records = br.by_key()
    names = ledger_instruments(src)
    # resolve() RAISES on an unmapped or ambiguous name, so the forward direction
    # is already total once this loop returns. The reverse is the one that needs
    # asserting: a panel no ledger name claims is a name nobody is checking.
    resolved = {n: br.resolve(n, records) for n in names}
    claimed = {(r.market, r.instrument) for r in resolved.values()}
    unclaimed = set(records) - claimed
    if unclaimed:
        raise AssertionError(f"{len(unclaimed)} panel(s) claimed by no ledger name: "
                             f"{sorted(unclaimed)} — add a LEDGER_ALIAS entry or a ledger row")

    lines = [START,
             "// One record per covered name: n = resolved non-overlapping 3-month",
             "// windows, c90 = share of them that finished inside the 90% band,",
             "// width = our 90% band / a simple no-forecast rule's (median) — the",
             "// sharpness half of the record. strength = long (>=40) / short (>=22) /",
             "// market-only. flag = narrow | wide | null (two-sided binomial, 5%).",
             "// Derivation of the thresholds: engine/band_record.py. NEVER hand-edit.",
             "const BANDS = {"]
    for n in names:
        r = resolved[n]
        key = n if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", n) else f'"{n}"'
        cov = "null" if r.cov90 is None else f"{r.cov90:.4f}"
        flag = "null" if r.flag is None else f'"{r.flag}"'
        lines.append(f'  {key}: {{mkt:"{r.market}", n:{r.n}, hits:{r.hits}, '
                     f'c50:{r.cov50:.4f}, c80:{r.cov80:.4f}, c90:{cov}, '
                     f'width:{r.width:.3f}, strength:"{r.strength}", flag:{flag}}},')
    lines.append("};")
    # Pooled market fallback, for the names whose own record is too short to read.
    lines.append("// Pooled per-market record: what a market-only name is judged on.")
    lines.append("const BAND_MARKETS = {")
    for m in sorted({r.market for r in resolved.values()}):
        mr = br.market_record(m)
        lines.append(f'  {m}: {{names:{mr["names"]}, n:{mr["n"]}, '
                     f'c90:{mr["cov90"]:.4f}, label:"{br.MARKET_LABEL[m]}"}},')
    lines.append("};")
    lines.append(END)
    return "\n".join(lines), resolved


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    src = open(DATA_JS, encoding="utf-8").read()
    block, resolved = build(src)

    if START in src:
        i, j = src.index(START), src.index(END) + len(END)
        out = src[:i] + block + src[j:]
    else:
        anchor = "const LEDGER = ["
        i = src.index(anchor)
        out = src[:i] + block + "\n\n" + src[i:]

    flagged = [(n, r) for n, r in resolved.items() if r.flag]
    strengths = {}
    for r in resolved.values():
        strengths[r.strength] = strengths.get(r.strength, 0) + 1
    print(f"{len(resolved)} names — " +
          ", ".join(f"{k}: {v}" for k, v in sorted(strengths.items())))
    for n, r in sorted(flagged, key=lambda x: x[1].flag or ""):
        print(f"  {r.flag.upper():6s} {n:12s} {r.chip()}")
    if not a.write:
        print("\n(dry run — pass --write)")
        return
    open(DATA_JS, "w", encoding="utf-8").write(out)
    # VERIFY BY LOAD, NOT BY PARSE — the standing rule, and the reason the
    # sibling registry generator does the same after every emit.
    subprocess.run(["node", "--check", DATA_JS], check=True)
    subprocess.run(["node", "-e", f"""
      const fs=require('fs'),vm=require('vm'),ctx={{}};vm.createContext(ctx);
      vm.runInContext(fs.readFileSync({DATA_JS!r},'utf8')+';globalThis.__X={{LEDGER,BANDS,BAND_MARKETS}};',ctx);
      const {{LEDGER,BANDS,BAND_MARKETS}}=ctx.__X;
      const miss=[...new Set(LEDGER.map(r=>r.instrument))].filter(n=>!(n in BANDS));
      if(miss.length) throw new Error('ledger names with no band record: '+miss.join(','));
      if(!Object.keys(BAND_MARKETS).length) throw new Error('BAND_MARKETS empty');
      console.log('data.js loads — '+Object.keys(BANDS).length+' records');
    """], check=True)
    print(f"wrote {DATA_JS}")


if __name__ == "__main__":
    main()
