#!/usr/bin/env python3
"""Negative control for [R-ENF-04]: prove the floor actually fires.

Reinjects the EXACT condition measured on 25-Aug-2026 — assets/data.js emptied to
a valid, loadable file holding zero entries — and asserts that every gate which
reads it now goes RED. Before [R-ENF-04] all three exited 0 and reported clean.

A check nobody has seen fail is not evidence; this is the standing proof, run in
CI beside the gates it backstops. It restores data.js and verifies the restore
byte-for-byte, so a crash cannot leave the book empty.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JS = os.path.join(ROOT, 'assets', 'data.js')

EMPTY = """const SITE = { updated: "2026-01-01" };
const TICKERS = {};
const METALS = {};
const LEDGER = [
];
const BANDS = {};
const BAND_MARKETS = {};
// ==== NAME_CALIBRATION (generated by engine/build_name_calibration.py — do not hand-edit) ====
const CALIB = {
};
// ==== END NAME_CALIBRATION ====
"""

GATES = ['check_page_integrity', 'check_data_freshness', 'check_technical_read']


def md5(path):
    return hashlib.md5(open(path, 'rb').read()).hexdigest()


def main() -> int:
    before = md5(DATA_JS)
    backup = os.path.join(tempfile.mkdtemp(prefix='r-enf-04-'), 'data.js')
    shutil.copy2(DATA_JS, backup)
    failures, caught = [], []
    try:
        open(DATA_JS, 'w', encoding='utf-8').write(EMPTY)
        # the injected file must be VALID JS — otherwise the gates would go red
        # for the wrong reason and the control would prove nothing.
        chk = subprocess.run(['node', '--check', DATA_JS], capture_output=True)
        if chk.returncode != 0:
            failures.append('the injected empty data.js is not valid JS — the '
                            'control would pass for the wrong reason')
        for g in GATES:
            r = subprocess.run([sys.executable, os.path.join(ROOT, 'scripts', f'{g}.py')],
                               capture_output=True, text=True, cwd=ROOT)
            if r.returncode == 0:
                failures.append(f'{g} reported CLEAN on an empty book (exit 0) '
                                '— [R-ENF-04] is not holding')
            else:
                first = (r.stdout + r.stderr).strip().splitlines()
                caught.append(f'{g}: exit {r.returncode} — '
                              f'{first[-1][:96] if first else "(no output)"}')
    finally:
        shutil.copy2(backup, DATA_JS)

    after = md5(DATA_JS)
    if after != before:
        failures.append(f'data.js was NOT restored ({before[:8]} -> {after[:8]})')

    for line in caught:
        print(f'  caught: {line}')
    if failures:
        print()
        for f in failures:
            print(f'FAIL  {f}')
        return 1
    print(f'\nnegative control OK — all {len(GATES)} gates go red on an empty '
          'book, and data.js restored byte-identical')
    return 0


if __name__ == '__main__':
    sys.exit(main())
