#!/usr/bin/env python3
"""PHAR — the far forecast years as RANGES, and the years that carry no range.

[R-FCAL-01] requires a run's updated fundamental analysis to publish YEARS THREE TO
FIVE AS RANGES from that record's own driver-error distribution, never as points, and
[R-FCAL-01 AMENDED 07-09-2026] requires every published band to declare its BASIS from
a closed list, the COUNT behind it and its ORIENTATION from the closed pair — because a
factor of 0.4 and a factor of 2.5 are each an ordinary thing to read on a page and only
the arithmetic behind them says which is meant.

WHAT THIS FILE DOES AND WHAT IT REFUSES TO DO. It reads the walk-forward's own committed
band record and the study's own committed forecast, multiplies one by the other, and
writes the result. IT INVENTS NOTHING. The run is LIGHT and tests one, two and three
years ahead, so the study's third forecast year has a measured band and its fourth and
fifth have NONE — and this file records that absence with the record's own stated
reason rather than extrapolating the three-year band out to five. A fabricated cell
would corrupt the very error it is scored on, and an honest absence, stated, is the
correct output.

EVERY FIGURE HERE IS COMPUTED. Not one number is typed into this module: the point path
comes from study_numbers.json, the factors and their counts from the band record, and
the horizon each forecast year sits at is derived from its position in the forecast.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RECORD = os.path.join(HERE, '..', 'phar_walkforward', 'forward_ranges.json')
OUT = os.path.join(HERE, 'far_year_ranges.json')

# The first forecast year sits ONE year beyond the last reported year, so the forecast
# year at index i is horizon i+1 on the walk-forward's own clock. Derived rather than
# typed: it is the same offset the run itself uses to pair a projection with an outturn.
FIRST_FORECAST_HORIZON = 1

# The lines a reader compares against Appendix A.1, each paired with the driver the run
# actually scored. A LINE IS ONLY LISTED WHERE THE TWO MEASURE THE SAME QUANTITY: the
# run's net_profit is GROUP profit for the year, before the non-controlling share, so the
# study's group figure is rebuilt from the attributable line and that share rather than
# the attributable line being scored against a group band.
LINES = [
    ('revenue', 'Revenue', 'revenue'),
    ('cogs', 'Cost of sales', 'cogs'),
    ('gross_profit', 'Gross profit', 'gross_profit'),
    ('net_profit', 'Profit for the year', 'net_profit'),
    ('dna', 'Depreciation and amortisation', 'dna'),
    ('capex', 'Capital expenditure', 'capex'),
]


def point_paths(study):
    """The study's own committed forecast, on the run's own definitions."""
    fc = study['forecast']
    nci = study['inputs']['nci_fwd']['value']
    return {
        'revenue': list(fc['revenue']),
        'cogs': list(fc['cogs']),
        'gross_profit': list(fc['gross_profit']),
        # group profit for the year = attributable profit + the non-controlling share the
        # model deducts to reach it. Frame A, which is the frame Appendix A.1 publishes.
        'net_profit': [p + nci for p in fc['parent']],
        'dna': list(fc['dna']),
        'capex': list(fc['capex']),
    }


def build():
    rec = json.load(open(RECORD, encoding='utf-8'))
    study = json.load(open(os.path.join(HERE, 'study_numbers.json'), encoding='utf-8'))
    years = study['forecast']['years']
    pts = point_paths(study)
    bands = rec['bands']

    far = []
    for i, year in enumerate(years):
        h = i + FIRST_FORECAST_HORIZON
        if h < 3:                      # years one and two are published as points
            continue
        entry = dict(year=year, horizon=h, index=i)
        if h in rec['horizons_covered']:
            entry['band'] = True
            entry['lines'] = {}
            for key, label, driver in LINES:
                cell = bands[driver][str(h)]
                pt = pts[key][i]
                entry['lines'][key] = dict(
                    label=label,
                    driver_scored=driver,
                    point=pt,
                    low=pt * cell['mult_low'],
                    high=pt * cell['mult_high'],
                    median=pt * cell['median_mult'],
                    factor_low=cell['mult_low'],
                    factor_high=cell['mult_high'],
                    factor_median=cell['median_mult'],
                    basis=cell['basis'],
                    n=cell['n'],
                    orientation=cell['orientation'])
        else:
            entry['band'] = False
            entry['reason'] = rec['horizons_not_covered']['h%d' % h]
        far.append(entry)

    return dict(
        _=('PHAR — the far forecast years as ranges. GENERATED by far_year_ranges.py from '
           'the walk-forward record and the study\'s own committed forecast; never '
           'hand-edited, and nothing here is typed.'),
        run=rec['run'],
        scope=rec['scope'],
        basis_list_closed=rec['basis_list_closed'],
        orientation_list_closed=rec['orientation_list_closed'],
        orientation=rec['orientation'],
        orientation_note=rec['orientation_note'],
        percentile_minimum_n=rec['percentile_minimum_n'],
        horizons_covered=rec['horizons_covered'],
        horizons_not_covered=rec['horizons_not_covered'],
        far_years=far)


if __name__ == '__main__':
    r = build()
    json.dump(r, open(OUT, 'w', encoding='utf-8'), indent=1)
    print('PHAR far-year ranges — basis, count and orientation carried on every published '
          'band\n')
    print('orientation: %s' % r['orientation'])
    print('scope: %s   horizons tested: %s\n'
          % (r['scope'], ', '.join(str(h) for h in r['horizons_covered'])))
    for e in r['far_years']:
        if not e['band']:
            print('%-9s horizon %d — NO BAND. %s' % (e['year'], e['horizon'], e['reason']))
            continue
        print('%-9s horizon %d' % (e['year'], e['horizon']))
        print('   %-32s %12s %12s %12s  %-6s %s'
              % ('line', 'low', 'as published', 'high', 'basis', 'n'))
        for _key, label, _drv in LINES:
            c = e['lines'][_key]
            print('   %-32s %12s %12s %12s  %-6s %d'
                  % (label, format(c['low'], ',.1f'), format(c['point'], ',.1f'),
                     format(c['high'], ',.1f'), c['basis'], c['n']))
    print('\nwrote %s' % os.path.basename(OUT))
